"""Shared mechanical-engineering-to-AI teaching registry."""
PHASES=[
 ("Inside the Pump","Pressure falls, bubbles form, and their collapse damages the impeller."),
 ("Listening to the Machine","A short recording captures a condition a human cannot monitor continuously."),
 ("Making Sound Visible","Waveforms become time-frequency spectrograms."),
 ("Training the Inspector","A 2D CNN learns normal, mild, and severe patterns."),
 ("Engineering Decision","Predictions become simulated maintenance responses."),
 ("Model Audit","Performance and limitations are checked honestly."),
]
STEPS=[
 dict(id="cavitation",phase=0,civil="What Happens Inside the Pump",ai="The Detection Target",tech="bubble formation and collapse",
 site="At low local pressure, liquid vaporises into bubbles near the impeller eye. Those bubbles move into higher-pressure regions and collapse violently.",
 challenge="Cavitation can erode the impeller, reduce efficiency, increase vibration, and shorten pump life before damage is visible externally.",
 ai_link="The collapsing bubbles produce distinctive broadband and impulsive sound. That acoustic signature becomes the observable target.",
 notebook="Generate labelled normal, mild, and severe pump recordings.",takeaway="Cavitation is a hydraulic phenomenon that leaves an acoustic signature."),
 dict(id="listen",phase=1,civil="A Short Pump Recording",ai="Audio Input",tech="2-5 second mono waveform",
 site="A microphone records several seconds of pump operation while RPM, inlet pressure, flow, and valve opening describe the test condition.",
 challenge="A person can hear obvious gravel-like noise, but continuous listening is impractical and early changes can be masked by motors, bearings, and background noise.",
 ai_link="Use only the recording as the CNN input. Engineering variables help generate or label examples but do not enter the image model.",
 notebook="Create four-second 8 kHz audio clips and store engineering metadata separately.",takeaway="The model listens to the sound; metadata explains how the sound was produced."),
 dict(id="waveform",phase=2,civil="Sound as Pressure Over Time",ai="Waveform Preprocessing",tech="remove mean; normalize amplitude",
 site="The microphone converts pressure fluctuations into a sequence of amplitude samples.",challenge="Raw loudness varies with microphone distance and gain, so volume alone must not become the classifier.",
 ai_link="Remove DC offset and normalize every clip to a common peak before extracting its frequency content.",
 notebook="Apply mean removal and peak normalization to every waveform.",takeaway="Normalize level so the CNN learns sound structure rather than microphone gain."),
 dict(id="spectrogram",phase=2,civil="Making Cavitation Visible",ai="Mel-Spectrogram",tech="STFT -> Mel bands -> log power",
 site="Normal rotation creates stable tonal bands. Bubble collapse adds scattered high-frequency energy and short bursts that change over time.",
 challenge="A waveform is too dense to interpret directly; frequency and timing are mixed into one line.",
 ai_link="A Mel-spectrogram separates frequency vertically and time horizontally, turning acoustic behaviour into a 2D image.",
 notebook="Compute a 64-band log Mel-spectrogram for every clip.",takeaway="The spectrogram reveals where acoustic energy occurs in frequency and time."),
 dict(id="cnn",phase=3,civil="An Automated Acoustic Inspector",ai="2D CNN",tech="Conv2D -> pool -> Conv2D -> pool -> dense",
 site="An engineer compares stable harmonic bands with broadband crackle and repeated impulsive events.",challenge="Hand-written frequency thresholds fail when RPM, load, microphone, and background noise change.",
 ai_link="Convolutional filters learn local time-frequency shapes and combine them into condition evidence without manually specifying every pattern.",
 notebook="Build a compact 2D CNN ending in three Softmax probabilities.",takeaway="A CNN treats the spectrogram as an image of machine behaviour."),
 dict(id="training",phase=3,civil="Learning From Labelled Pump Tests",ai="Supervised Training",tech="cross-entropy + Adam + early stopping",
 site="Controlled tests provide examples labelled Normal, Mild Cavitation, and Severe Cavitation.",challenge="Randomly splitting near-duplicate clips can make accuracy look better than performance on a genuinely new pump run.",
 ai_link="Train on earlier generated runs, validate separately, and reserve unseen clips for the final audit.",
 notebook="Train with sparse categorical cross-entropy and early stopping.",takeaway="A trustworthy test set must represent recordings the model did not learn by heart."),
 dict(id="prediction",phase=4,civil="From Sound to Pump Condition",ai="Softmax Prediction",tech="Normal / Mild / Severe + confidence",
 site="The maintenance team needs one condition assessment and evidence strong enough to decide whether to inspect.",challenge="A class name alone hides uncertainty and can encourage false confidence in noisy or unfamiliar conditions.",
 ai_link="Report all three probabilities, highlight the largest, and attach a simulated educational response.",
 notebook="Classify a test recording and display confidence with its spectrogram.",takeaway="A prediction supports inspection; it does not operate industrial equipment."),
 dict(id="audit",phase=5,civil="The Mechanical Engineering Audit",ai="Confusion Matrix and Limitations",tech="accuracy, per-class recall, confusion matrix",
 site="Missing severe cavitation is more consequential than confusing mild cavitation with severe cavitation.",challenge="Overall accuracy can hide a model that performs badly on the most important class or on a different pump and microphone.",
 ai_link="Inspect the confusion matrix and per-class recall, then state domain-shift and synthetic-data limitations explicitly.",
 notebook="Report accuracy, classification report, and confusion matrix on unseen clips.",takeaway="Audit the errors that matter mechanically, not only the total number correct."),
]
BY_ID={s["id"]:s for s in STEPS}; ORDER=[s["id"] for s in STEPS]

