PHASES=[("The Connected Flood Problem","Water moves between road sections, so risk is not independent."),("Building the City Graph","Road sections become nodes and connections become edges."),("Simulating Storms","A virtual network produces labelled flood scenarios."),("Learning From Neighbours","Graph convolutions combine local and connected-road evidence."),("Ranking Vulnerable Roads","Node probabilities identify where flooding is likely to begin."),("Civil Engineering Audit","Baselines, reasons, uncertainty, and deployment limits are explicit.")]
STEPS=[
dict(id="problem",phase=0,civil="Which Road Floods First?",ai="Node-Level Flood Prediction",tech="risk for every connected road section",site="During intense rainfall, water accumulates differently across roads because elevation, drainage, slope, and incoming flow vary.",challenge="Monitoring current depth alone can miss a low road that is still shallow but is about to receive water from several neighbours.",ai_link="Predict a flood probability for every road before depths become impassable, then rank the likely sequence.",notebook="Define node-level flood risk and the road-ranking output.",takeaway="The earliest vulnerable road may not be the wettest road right now."),
dict(id="graph",phase=1,civil="Roads as a Connected Network",ai="Graph Representation",tech="nodes = roads; edges = connections",site="Intersections and connecting road segments provide paths through which surface water and traffic effects propagate.",challenge="A table of isolated rows discards which road can send water toward which neighbour.",ai_link="Represent each road section as a node and hydraulic/physical connections as graph edges.",notebook="Create a 30-node virtual road graph and adjacency matrix.",takeaway="Connectivity is an engineering input, not merely a drawing."),
dict(id="features",phase=1,civil="Five Measurements Per Road",ai="Node Features",tech="rain, elevation, depth, drainage, slope",site="Each road has rainfall intensity, elevation, current water depth, drainage capacity, and slope.",challenge="Raw units differ, and slope direction affects whether a neighbour is upstream or downstream.",ai_link="Store five normalized features on every node while the graph stores who can influence whom.",notebook="Assemble an N×5 feature matrix and retain physical units for interpretation.",takeaway="Node features describe the road; edges describe its context."),
dict(id="simulate",phase=2,civil="Virtual Urban Storms",ai="Synthetic Graph Dataset",tech="mass-balance-inspired runoff and neighbour inflow",site="A teaching city can be subjected to many storms while road elevations and drainage capacities remain fixed.",challenge="Random labels would not demonstrate why the graph matters.",ai_link="Simulate runoff, drainage removal, and elevation-directed neighbour transfer to create flood labels.",notebook="Generate hundreds of graph snapshots with node-level risk classes.",takeaway="Synthetic labels should depend on both local conditions and connected upstream water."),
dict(id="adjacency",phase=2,civil="How Neighbour Influence Is Weighted",ai="Normalized Adjacency",tech="Â = D⁻½(A+I)D⁻½",site="Every road keeps its own information while also receiving evidence from connected sections.",challenge="Simply summing neighbours makes high-degree intersections numerically dominate.",ai_link="Add self-connections and degree-normalize the adjacency matrix before graph convolution.",notebook="Calculate normalized adjacency and inspect one road's neighbourhood.",takeaway="Normalization balances self-information and neighbour messages."),
dict(id="gcn",phase=3,civil="Learning From This Road and Its Neighbours",ai="Graph Convolutional Network",tech="H′ = ReLU(ÂHW)",site="Road C may be low and poorly drained while Road B and Road E are sending it additional water.",challenge="An MLP sees Road C alone and cannot distinguish identical local readings embedded in different networks.",ai_link="GCN layers aggregate connected-node features, transform them, and pass updated representations through the graph.",notebook="Build two pure-TensorFlow graph-convolution layers and a node classifier.",takeaway="The GNN learns from conditions and connections simultaneously."),
dict(id="training",phase=3,civil="Learning Across Many Storms",ai="Node Classification Training",tech="weighted cross-entropy + validation",site="Each simulated storm labels every road as Low, Medium, or High risk.",challenge="Most roads may remain safe, so unweighted accuracy can ignore the rare high-risk nodes.",ai_link="Train on graph snapshots, monitor validation loss, and report class-specific recall.",notebook="Train the GCN on balanced/weighted node labels.",takeaway="A flood model must be judged on high-risk roads, not only the safe majority."),
dict(id="ranking",phase=4,civil="Flooding Order and Main Reasons",ai="Risk Ranking",tech="sort node high-risk probability",site="Authorities need a prioritized list for inspection, traffic diversion, and drainage response.",challenge="A probability without network context gives little insight into why one road ranks above another.",ai_link="Sort high-risk probabilities and display local elevation/drainage plus connected upstream-water evidence.",notebook="Map probabilities, print the top-five order, and explain the leading road.",takeaway="Ranking converts thirty node predictions into an actionable inspection priority."),
dict(id="audit",phase=5,civil="The Urban Drainage Audit",ai="GNN vs Isolated-Road Baseline",tech="confusion matrix, high-risk recall, ablation",site="A graph model is justified only if connectivity improves decisions over a model that sees each road independently.",challenge="Synthetic topology and simplified surface flow may not transfer to a real city's drains, kerbs, inlets, terrain, and blockages.",ai_link="Compare against an MLP baseline, remove edges as an ablation, inspect high-risk misses, and state mapping limits.",notebook="Report metrics, connectivity benefit, uncertainty, and real-data requirements.",takeaway="The graph must earn its complexity through measurable neighbour-information value.")]
BY_ID={s["id"]:s for s in STEPS};ORDER=[s["id"] for s in STEPS]

