PHASES=[("The Engine Snapshot","Seven readings must be interpreted together."),("Preparing Sensor Records","Operating regimes become clean, scaled rows."),("Choosing the Network","Independent tabular snapshots suit an MLP."),("Learning Conditions","Dense layers learn five combined sensor patterns."),("Engineering Response","Probabilities become a simulated recommendation."),("Model Audit","Class errors, confidence, and limits are reviewed.")]
STEPS=[
dict(id="problem",phase=0,civil="Seven Gauges, One Condition",ai="Operating-State Classification",tech="combine readings into one condition",site="An engine operator sees speed, load, cooling, intake, fuel, pressure, and exhaust measurements at the same moment.",challenge="One value can appear acceptable while the combination indicates overheating, inefficient combustion, overload, or another abnormal state.",ai_link="Learn the joint relationship among seven readings and return one current operating-condition probability distribution.",notebook="Define the five conditions and seven-input snapshot.",takeaway="The condition exists in the combination, not necessarily in one gauge."),
dict(id="inputs",phase=0,civil="The Seven Engine Measurements",ai="Input Features",tech="RPM, load, coolant, intake, fuel, pressure, exhaust",site="Each sensor describes a different part of engine operation: mechanical demand, thermal state, airflow, fuelling, intake pressure, and combustion temperature.",challenge="The features use different units and ranges, so numerical magnitude is not the same as engineering importance.",ai_link="Keep all seven named columns and preserve their units for interpretation before scaling copies for the network.",notebook="Create the feature list and inspect representative rows.",takeaway="Named engineering features make the MLP input explainable."),
dict(id="data",phase=1,civil="Engine Operating Regimes",ai="Synthetic Labelled Dataset",tech="five physically distinguishable distributions",site="Controlled tests label examples as Normal, High Load, Overheating, Inefficient Operation, or Abnormal.",challenge="Purely random labels would let the notebook run but teach no meaningful engineering relationship.",ai_link="Generate overlapping regimes from reasonable educational ranges and include noise so no single threshold solves every row.",notebook="Build a balanced synthetic dataset and inspect class distributions.",takeaway="Synthetic regimes should overlap realistically while remaining auditable."),
dict(id="prepare",phase=1,civil="Checking and Scaling the Log",ai="Cleaning and Normalization",tech="impute training median; StandardScaler",site="Sensors can miss readings and RPM is numerically much larger than pressure or fuel flow.",challenge="An MLP cannot accept missing values, and scaling on the full dataset leaks test information.",ai_link="Split first, learn imputation and scaling parameters from training rows only, then transform validation and test rows.",notebook="Handle missing data and standardize seven inputs without leakage.",takeaway="Preprocessing parameters are learned components of the deployed model."),
dict(id="mlp",phase=2,civil="Choosing the Right Neural Network",ai="Multilayer Perceptron",tech="7 -> Dense32 -> Dense16 -> Softmax5",site="The question concerns one synchronized sensor snapshot, not an image, waveform, or long history.",challenge="Using a more fashionable architecture adds complexity without matching the structure of the data.",ai_link="Dense layers are appropriate because every feature can interact with every other feature in the same row.",notebook="Build a compact MLP and contrast its input assumptions with CNN and LSTM models.",takeaway="Architecture should follow data structure, not fashion."),
dict(id="training",phase=3,civil="Learning Combined Operating Patterns",ai="Supervised Classification",tech="cross-entropy + Adam + early stopping",site="Each labelled test records the engine condition that produced its sensor combination.",challenge="Class imbalance or repeated data can make accuracy misleading, especially for the broad Abnormal category.",ai_link="Use balanced classes, stratified splits, validation monitoring, and class-specific test metrics.",notebook="Train the MLP and plot loss and accuracy.",takeaway="The test set must represent operating rows the network did not optimize against."),
dict(id="prediction",phase=4,civil="Current Engine Condition",ai="Softmax Probabilities",tech="five classes + confidence + simulated action",site="The engineer needs a concise condition and an appropriate next inspection or load-management response.",challenge="The largest probability can still be uncertain, and a classroom label must not directly control machinery.",ai_link="Display all probabilities, identify the highest, and attach a transparent simulated recommendation outside the MLP.",notebook="Predict an entered sensor row and print condition, confidence, and simulated response.",takeaway="The MLP classifies; the recommendation layer remains visible and reviewable."),
dict(id="audit",phase=5,civil="The Engine Monitoring Audit",ai="Confusion Matrix and Confidence Review",tech="accuracy, per-class recall, uncertain cases",site="Confusing High Load with Overheating has a different consequence from confusing Normal with Abnormal.",challenge="Overall accuracy hides class-specific misses and overconfident predictions on unfamiliar sensor combinations.",ai_link="Inspect the confusion matrix, per-class recall, calibration-style confidence bins, and out-of-range warnings.",notebook="Report test metrics and state synthetic-data and deployment limitations.",takeaway="A useful classifier must reveal where it is uncertain and where its training domain ends.")]
BY_ID={s["id"]:s for s in STEPS};ORDER=[s["id"] for s in STEPS]

