"""Shared teaching scaffold for the notebook and Streamlit companion."""

PHASES = [
    ("The Station", "A route that is safe now may flood before passengers reach the exit."),
    ("Reading the Water", "Five measurements describe how water enters, accumulates, and drains."),
    ("Remembering the Storm", "Recent measurements become a sequence rather than isolated rows."),
    ("Forecasting Five Minutes", "An LSTM predicts future route depth."),
    ("Choosing the Exit", "Two forecasts become one actionable evacuation recommendation."),
    ("Engineering Audit", "The forecast and decision are checked honestly."),
]

STEPS = [
    dict(id="station", phase=0, civil="A Station During Heavy Rain", ai="Why Prediction Is Needed",
         tech="Current safety is not future safety",
         site="Passengers are on an underground platform with two evacuation routes. Both routes can look usable while water is entering through the station entrance and tunnel.",
         challenge="Evacuation takes time. A route selected from its current water depth can become unsafe while passengers are still moving through it.",
         ai_link="Forecast the depth five minutes ahead, early enough to redirect passengers before the route deteriorates.",
         notebook="Define the two-route station and the five-minute forecasting target.",
         takeaway="Choose a route for the conditions passengers will meet, not only those visible now."),
    dict(id="inputs", phase=1, civil="Five Flood Measurements", ai="Input Features",
         tech="rainfall, entrance, tunnel, drainage, route depth",
         site="Rain supplies water; entrance and tunnel levels describe where it is arriving; drains remove it; the route level shows what has already accumulated.",
         challenge="No single measurement describes the balance. Heavy rain may be manageable with strong drainage, while moderate rain can be dangerous when the drains are overloaded.",
         ai_link="The model receives only these five measurements so every prediction remains explainable in engineering terms.",
         notebook="Generate one-minute measurements for Routes A and B.",
         takeaway="Flood risk is the balance between water entering, water leaving, and water already stored."),
    dict(id="prepare", phase=1, civil="Checking the Instrument Log", ai="Cleaning and Normalization",
         tech="interpolate gaps; fit scaler on training data",
         site="A level sensor may miss a reading and every instrument uses different units. Engineers check the log before trusting it.",
         challenge="An LSTM cannot interpret a missing value, and rainfall in mm/hr can dominate route depth in centimetres simply because its numbers are larger.",
         ai_link="Interpolate short gaps and scale all five inputs using statistics learned from training data only.",
         notebook="Clean the synthetic log and apply MinMaxScaler without test leakage.",
         takeaway="A clean, consistently scaled sequence is part of the model, not clerical preparation."),
    dict(id="sequences", phase=2, civil="The Previous Ten Minutes", ai="Time Sequences",
         tech="10 x 5 input window -> depth at t+5",
         site="A rising route level means something different after ten minutes of heavy rain than after ten minutes of recovery.",
         challenge="A row-by-row model sees the present snapshot but loses the direction and persistence of the storm.",
         ai_link="Each training example contains the previous ten one-minute readings and the route depth five minutes after the final reading.",
         notebook="Convert the continuous log into sliding windows and future-depth targets.",
         takeaway="Flooding is a process, so the model must see a history."),
    dict(id="lstm", phase=2, civil="Remembering Accumulation", ai="LSTM Memory",
         tech="gates retain, update, and expose useful state",
         site="Water on a route is stored history: earlier inflow still matters until drainage removes it.",
         challenge="Recent measurements are not equally useful. The model must retain a sustained rise and forget noise or an old shower that has already drained.",
         ai_link="An LSTM learns gates that decide what history to keep, update, and use for the forecast.",
         notebook="Build an LSTM(32) followed by Dense layers and one regression output.",
         takeaway="LSTM memory represents the evolving balance of accumulation and drainage."),
    dict(id="training", phase=3, civil="Learning From Recorded Storms", ai="Model Training",
         tech="MAE loss + Adam optimizer + early stopping",
         site="Recorded storm events show how route water actually responded to different rainfall and drainage conditions.",
         challenge="The model must learn the relationship without memorising one storm or training indefinitely on noise.",
         ai_link="Train on earlier sequences, validate on later ones, and stop when validation error no longer improves.",
         notebook="Train the LSTM with MAE loss and EarlyStopping.",
         takeaway="Training adjusts the forecast; validation tells us when adjustment stops helping."),
    dict(id="forecast", phase=3, civil="Water Depth Five Minutes Ahead", ai="Regression Forecast",
         tech="one continuous output in centimetres",
         site="The control room needs an estimated depth, not merely a vague danger label.",
         challenge="A label hides how close the route is to a decision boundary and prevents engineers from applying a different project rule.",
         ai_link="The LSTM outputs a continuous depth in centimetres; a separate project assumption converts it into a safety band.",
         notebook="Inverse-transform the prediction and plot actual versus predicted depth.",
         takeaway="Predict the physical quantity first; apply the operational rule second."),
    dict(id="thresholds", phase=4, civil="Project Safety Bands", ai="Decision Thresholds",
         tech="<10 safe; 10-20 warning; >20 unsafe",
         site="The demonstration needs a clear rule for when a route should no longer be selected.",
         challenge="There is no universal evacuation-depth standard established by this educational model; presenting one as universal would be unsafe.",
         ai_link="Use explicit project assumptions: below 10 cm SAFE, 10-20 cm WARNING, above 20 cm UNSAFE. A real project requires authority approval and site-specific analysis.",
         notebook="Implement a transparent status function separate from the LSTM.",
         takeaway="Thresholds are declared project assumptions, not facts learned by the model."),
    dict(id="routes", phase=4, civil="Route A Versus Route B", ai="Decision Fusion",
         tech="forecast both routes; choose lowest acceptable depth",
         site="The platform has two exits. Route A may receive entrance water while Route B remains protected by stronger drainage.",
         challenge="A prediction becomes useful only when it changes the evacuation decision before conditions become dangerous.",
         ai_link="Forecast both routes with the same five inputs, classify each using the assumed bands, and recommend the safer usable route.",
         notebook="Compare Route A and Route B predictions and print the recommendation.",
         takeaway="The final output is an actionable route recommendation, supported by two forecasts."),
    dict(id="audit", phase=5, civil="The Engineering Audit", ai="Forecast Evaluation",
         tech="MAE, RMSE, threshold errors, time-ordered test",
         site="Before an evacuation system is trusted, engineers ask how far forecasts miss and whether those misses change the route decision.",
         challenge="A low average error can still hide dangerous cases where an unsafe route is predicted as safe.",
         ai_link="Evaluate on later, unseen storm periods using MAE and RMSE, then count safety-band and unsafe-as-safe errors separately.",
         notebook="Report regression metrics and decision-confusion counts on the test period.",
         takeaway="Audit the consequence of error, not only its average size."),
]

BY_ID = {s["id"]: s for s in STEPS}
ORDER = [s["id"] for s in STEPS]

