"""Shared Mechanical Design -> Generative AI teaching registry."""
PHASES=[("The Design Brief","A bracket must connect fixed mounts while using material efficiently."),("Geometry as Data","Every silhouette becomes a 64×64 occupancy grid."),("Learning a Design Language","A VAE compresses and reconstructs bracket families."),("Exploring Alternatives","New latent points decode into unseen geometries."),("Engineering Screening","Connectivity and mounting constraints reject unusable shapes."),("Design Review","Material reduction and limitations are audited.")]
STEPS=[
dict(id="brief",phase=0,civil="The Lightweight Bracket Brief",ai="Generative Design Objective",tech="preserve mounts; reduce material",site="A mechanical bracket transfers load between fixed mounting locations. Its holes and support paths must remain while excess material is a candidate for removal.",challenge="Drawing only one lighter shape explores little of the design space, while removing material without a load path can produce an unusable component.",ai_link="Learn common bracket geometry from examples, generate alternatives, and screen them before comparing material use.",notebook="Define the baseline bracket, fixed mounting zones, and educational screening rules.",takeaway="Generation proposes geometry; engineering checks decide whether it deserves consideration."),
dict(id="pixels",phase=1,civil="Bracket Geometry as a Grid",ai="Binary Occupancy Image",tech="64×64: 1 material, 0 empty",site="A silhouette records where material exists in a two-dimensional bracket profile.",challenge="CAD solids are too complex for a first generative notebook, but geometry must still be represented consistently across designs.",ai_link="Rasterize every profile onto a 64×64 grid: white pixels are material and black pixels are empty space.",notebook="Create and display binary bracket masks with fixed holes.",takeaway="An occupancy grid turns geometry into data while keeping the design visually interpretable."),
dict(id="dataset",phase=1,civil="A Family of Existing Brackets",ai="Training Dataset",tech="procedural variations of width, curvature, holes",site="A design archive contains related brackets with different webs, outer envelopes, lightening holes, and support ribs.",challenge="A VAE cannot learn a design language from one component; it needs enough valid variation to distinguish essential structure from optional material.",ai_link="Generate hundreds of connected bracket silhouettes while keeping the same mounting zones and varying noncritical geometry.",notebook="Build a reproducible synthetic dataset of valid 64×64 masks.",takeaway="The training set defines the design family the VAE can plausibly explore."),
dict(id="encoder",phase=2,civil="Summarising Each Design",ai="Encoder",tech="4096 pixels -> mean and log variance",site="Engineers describe a bracket through a few characteristics such as web thickness, hole size, curvature, and support distribution.",challenge="The image contains 4096 pixels, most of which are redundant descriptions of the same geometric choices.",ai_link="Convolutional layers compress the silhouette into parameters of a small latent distribution.",notebook="Build the convolutional encoder and inspect its mean and log-variance outputs.",takeaway="The encoder converts a detailed shape into a compact design description."),
dict(id="latent",phase=2,civil="A Continuous Design Space",ai="Variational Latent Representation",tech="z = μ + σ·ε",site="Useful design parameters change smoothly: a web can widen, a hole can move, or an outer curve can become more pronounced.",challenge="A normal autoencoder may leave gaps between known designs, so arbitrary latent points can decode unpredictably.",ai_link="The VAE regularises encodings toward a continuous distribution and samples with the reparameterisation trick.",notebook="Use a 16-variable latent vector and combine reconstruction and KL losses.",takeaway="A structured latent space makes interpolation and sampling meaningful."),
dict(id="decoder",phase=2,civil="Rebuilding the Bracket",ai="Decoder",tech="latent vector -> 64×64 probability map",site="A useful compressed description must reconstruct the material boundary, mounting zones, and support paths.",challenge="Too much compression blurs holes or breaks thin webs; too little regularisation merely memorises training images.",ai_link="Transpose-convolution layers expand the sampled vector into a pixelwise material probability map.",notebook="Train the VAE and compare original masks with reconstructions.",takeaway="Reconstruction quality shows what geometric information the latent representation retained."),
dict(id="generate",phase=3,civil="Creating New Alternatives",ai="Latent Sampling",tech="sample z -> decoder -> threshold",site="Design exploration requires alternatives not copied directly from the archive.",challenge="A generated probability image is not yet a manufacturable profile and can change drastically with threshold choice.",ai_link="Sample latent vectors, decode them, apply a declared binary threshold, and preserve the unthresholded probability for review.",notebook="Generate a gallery of previously unseen bracket silhouettes.",takeaway="The VAE generates candidates, not certified components."),
dict(id="screen",phase=4,civil="Checking the Load Path",ai="Geometry Validation",tech="mount coverage + connected-component test",site="Both mounting regions must remain connected by material for the bracket to have even a plausible load path.",challenge="Pixel count alone rewards empty or disconnected images, which appear light only because they have ceased to function as brackets.",ai_link="Reject candidates that lose mount coverage or whose required regions are not part of one connected material component.",notebook="Run connected-component and fixed-mount checks on each generated mask.",takeaway="Validity constraints must come before lightweight ranking."),
dict(id="rank",phase=5,civil="Selecting a Lighter Candidate",ai="Material-Area Ranking",tech="mass proxy = material pixels",site="For equal material and thickness, profile area is proportional to mass, making pixel count a simple first comparison.",challenge="Area is not stress, stiffness, buckling resistance, fatigue life, manufacturability, or safety factor.",ai_link="Rank only valid candidates by material pixels and report reduction relative to the baseline as a simulation result.",notebook="Create the candidate table, select the lightest valid mask, and state the limits of the proxy.",takeaway="A lighter valid silhouette is a candidate for analysis—not an approved engineering design.")]
BY_ID={s["id"]:s for s in STEPS};ORDER=[s["id"] for s in STEPS]

