PHASES=[("Choosing a Wall System","Site constraints make different wall systems suitable."),("Encoding Engineering Judgement","Educational design tendencies become reviewable labels."),("Learning Suitability","An MLP ranks four alternatives from five tabular inputs."),("Balancing Cost","A transparent optimizer combines suitability and estimated cost."),("Reviewing the Recommendation","Rankings, sensitivity, and limitations remain visible.")]
STEPS=[
dict(id="problem",phase=0,civil="The Retaining-Wall Choice",ai="Engineering Recommender",tech="four alternatives under competing constraints",site="A project may use a gravity, cantilever RCC, anchored, or MSE wall.",challenge="The most suitable option changes with height, soil, groundwater, available width, and budget.",ai_link="Rank the alternatives consistently while keeping the final engineering decision reviewable.",notebook="Define a multiclass recommendation task plus a separate cost layer.",takeaway="Recommendation narrows alternatives; it does not complete geotechnical or structural design."),
dict(id="inputs",phase=0,civil="Five Site Inputs",ai="Tabular Features",tech="height, soil, groundwater, width, budget",site="Each case is represented by wall height, soil type, groundwater condition, available width, and budget.",challenge="Three features are categorical and site width may rule out otherwise attractive systems.",ai_link="Encode categories and preserve the physical meaning of height and available width.",notebook="Create and inspect the five required inputs.",takeaway="A concise feature set makes assumptions easier to audit."),
dict(id="labels",phase=1,civil="Engineering Suitability Rules",ai="Training Labels",tech="declared educational tendencies",site="Low walls with space may favour gravity walls; moderate heights may favour cantilever walls; constrained high walls may favour anchors; wide reinforced fills may favour MSE.",challenge="These tendencies are not universal design rules and cannot replace checks for stability, drainage, bearing, reinforcement, or constructability.",ai_link="Use declared scoring rules to generate overlapping simulated labels and retain every class.",notebook="Build a transparent label generator for four wall types.",takeaway="A supervised model learns the judgement encoded in its labels."),
dict(id="data",phase=1,civil="Simulated Retaining-Wall Cases",ai="Synthetic Dataset",tech="plausible ranges and overlapping classes",site="Training examples span varied heights, soils, groundwater, widths, and budget levels.",challenge="Perfect deterministic labels would exaggerate model performance and hide uncertainty near design boundaries.",ai_link="Add controlled variation and split off unseen test cases.",notebook="Generate the dataset and audit class balance.",takeaway="Synthetic data demonstrates workflow, not field validation."),
dict(id="prepare",phase=2,civil="Preparing Mixed Site Data",ai="Leakage-Safe Preprocessing",tech="one-hot encoding plus standardization",site="Numerical and categorical attributes require different preparation.",challenge="Encoding or scaling on the complete dataset leaks test information.",ai_link="Fit transformations only on training data using a reusable preprocessing pipeline.",notebook="One-hot encode categories and scale numerical features.",takeaway="The deployed recommender must reuse the training transformations."),
dict(id="model",phase=2,civil="Ranking Wall Alternatives",ai="MLP Classifier",tech="encoded inputs -> Dense32 -> Dense16 -> Softmax4",site="Engineers need a ranked shortlist rather than a single unexplained label.",challenge="The largest probability can still be weak or sensitive to small input changes.",ai_link="Train a compact MLP and retain all four softmax probabilities.",notebook="Train the MLP with early stopping and plot learning curves.",takeaway="Probability ranking is useful evidence, not proof of suitability."),
dict(id="audit",phase=2,civil="Checking the Recommender",ai="Model Audit",tech="accuracy, confusion matrix, calibration clues",site="Confusion between adjacent alternatives can expose ambiguous site conditions.",challenge="Accuracy alone hides which wall types are confused and whether confidence is overstated.",ai_link="Inspect held-out predictions, confusion matrix, class metrics, and uncertain cases.",notebook="Evaluate unseen cases and display a full ranked prediction.",takeaway="Audit class-specific behaviour before using recommendations."),
dict(id="cost",phase=3,civil="Suitability Versus Cost",ai="Transparent Cost Optimization",tech="alpha*suitability - beta*normalized cost",site="A technically strong alternative may be unaffordable, while the cheapest option may be unsuitable.",challenge="Cost assumptions differ by location, quantities, access, drainage, and market conditions.",ai_link="Estimate illustrative costs, normalize them, and expose alpha and beta rather than hiding the trade-off.",notebook="Combine predicted suitability with estimated cost and rank alternatives.",takeaway="Cost modifies a technically screened shortlist; it must not rescue an unsafe option."),
dict(id="review",phase=4,civil="Engineering Decision Review",ai="Sensitivity and Human Approval",tech="input scenarios, ranking stability, limitations",site="Final selection requires surveys, soil investigation, calculations, drainage design, codes, constructability, lifecycle cost, and professional approval.",challenge="A recommendation can change near category boundaries or under different cost weights.",ai_link="Run sensitivity scenarios, show reasons and limitations, and require an engineer to approve or reject the shortlist.",notebook="Compare scenarios and produce the final educational decision card.",takeaway="The AI is a concept-screening assistant, not a retaining-wall designer.")]
BY_ID={s["id"]:s for s in STEPS};ORDER=[s["id"] for s in STEPS]
