"""The teaching registry: one entry per page, in the order the notebook works.

Every entry keeps the same five parts as the notebook's sections, and the same
plain-English house style: short sentences, everyday words.
  scene     - what is happening in the room, with no AI in it
  challenge - why that is hard for the person doing it
  ai_link   - what the AI is actually being asked to do
  tech      - the one-line technical idea
  plain     - the technical name in everyday words, for a first-time reader
  notebook  - which notebook section this matches
  takeaway  - one sentence to remember

'plain' exists because every page heading carries a term of art - "pose
keypoints", "chest compression fraction", "peak finder". A student meeting
those for the first time should never have to guess, so each page says what
its own jargon means before it uses it.

No computed figure is quoted in this prose. Every number on a page is worked
out by that page, so the two can never drift apart.
"""

PHASES = [
    ("The First Four Minutes", "Somebody has collapsed and nobody here is trained."),
    ("Which Sensor Answers What", "The split the whole design is built on."),
    ("Reading The Compressions", "Finding the pushes, then measuring them."),
    ("What The Unit Says", "One message at a time, and a beat to follow."),
    ("The Whole Session", "Tiring, swapping, hands-off time, and the AED."),
    ("The Handover", "The picture a paramedic gets, and what it would get wrong."),
]

STEPS = [
    dict(id="collapse", phase=0, scene="Nobody Here Is Trained", ai="The Real Problem",
         tech="a wall unit with a camera, a pad, a speaker, an AED and three lights",
         site="Someone collapses in a station concourse. A stranger kneels down, phone in one "
              "hand, and pulls a unit off the wall. They have never done this before.",
         challenge="Ambulances take minutes. Whatever happens in those minutes happens because a "
                   "frightened bystander did it, and they have no way of knowing whether what "
                   "they are doing is working.",
         ai_link="The unit is not diagnosing anybody. It is watching one person's technique and "
                 "telling them the single most useful thing to change right now.",
         plain="'Bystander CPR' just means chest compressions given by whoever happens to be there, "
               "before any ambulance arrives. Most of the people who give it have never been trained.",
         notebook="The opening - what the unit is and what the four minutes are for.",
         takeaway="Mediocre compressions are enormously better than none. The job is to nudge "
                  "them upward without stopping them."),

    dict(id="sensors", phase=1, scene="Camera, Pad Or AED?", ai="The Sensor Split",
         tech="camera for posture · pad for depth and rate and recoil · AED for rhythm",
         site="The obvious design is to point a camera at the helper and measure everything from "
              "the video. That design is wrong, and it is worth being precise about why.",
         challenge="Turning pixels into centimetres of chest travel depends on lens, angle, "
                   "distance, clothing and body size. A twenty percent error there is the "
                   "difference between effective CPR and useless CPR.",
         ai_link="Give each question to the sensor that can actually answer it, and refuse to "
                 "let the convenient sensor answer the hard question.",
         plain="A 'sensor' is anything that measures the world and turns it into numbers. The whole "
               "design question on this page is which measurement you are entitled to trust.",
         notebook="The framing table at the top of the notebook.",
         takeaway="Most of the engineering in a safe system is deciding what each part is not "
                  "allowed to do."),

    dict(id="rescue", phase=1, scene="Three And A Half Minutes", ai="The Simulated Session",
         tech="two helpers, one AED pause, two different ways of being wrong",
         site="Rescuer A starts well and tires. The AED interrupts for twelve seconds. Rescuer B "
              "takes over fresh, and starts far too slow.",
         challenge="Real training data comes from a mannequin in a classroom, where nobody is "
                   "frightened and nothing goes wrong by surprise.",
         ai_link="Generate the session instead, so every problem the unit must catch is present "
                 "on purpose and we know the right answer for each one.",
         plain="A 'simulation' means every number in this app is generated by code, not recorded from a "
               "real emergency. It lets us study the method without ever touching real patient data.",
         notebook="Section 2 - simulating the rescue.",
         takeaway="A degrades gradually, which is hard to notice from inside. B is wrong "
                  "immediately, which is easy to fix once somebody says so."),

    dict(id="pad", phase=1, scene="What The Pad Feels", ai="The Depth Signal",
         tech="fifty samples a second of how far the chest is pressed in",
         site="One compression is one push and one release. The pad reports the depth of the "
              "chest continuously, so a compression is a bump in a line.",
         challenge="At the scale of the whole rescue every compression is a single vertical "
                   "stroke and nothing can be read from it at all.",
         ai_link="Zoom in on five seconds and the three failures become visible: lower peaks, "
                 "closer together, and troughs that no longer come back to the floor.",
         plain="The 'depth signal' is one number, fifty times a second: how far down the chest is at "
               "this instant. Everything the coach says is worked out from that single line.",
         notebook="Section 2.1 - the pad signal.",
         takeaway="Nothing in this signal is subtle once you look at the right timescale. The "
                  "helper simply cannot see it while they are doing it."),

    dict(id="camera", phase=1, scene="What The Camera Sees", ai="Pose Keypoints",
         tech="wrist, elbow, shoulder as coordinates in centimetres",
         site="A pose model returns points. Everything the camera contributes is arithmetic on "
              "the positions of three of them.",
         challenge="A camera cannot tell whether the chest went down five centimetres. It can "
                   "tell perfectly well whether the arms are straight and the shoulders are over "
                   "the hands.",
         ai_link="Keep the camera on the questions it is good at, and let the answers steer the "
                 "helper's body rather than measure the patient's chest.",
         plain="'Pose keypoints' are the dots a vision model puts on a body - shoulder, elbow, wrist. It "
               "does not see a person; it sees seventeen labelled points and their positions.",
         notebook="Section 3 - what the camera sees.",
         takeaway="Straight arms mean body weight is doing the work. Bent arms mean the helper "
                  "is, and they will not last two minutes."),

    dict(id="elbow", phase=1, scene="The Angle At The Elbow", ai="Geometry, And Jitter",
         tech="the angle between elbow-to-shoulder and elbow-to-wrist",
         site="Three points, one angle. Straight arms come out close to 180 degrees.",
         challenge="The three points sit almost on a straight line, so a few millimetres of "
                   "keypoint wobble swings the measured angle a long way.",
         ai_link="Average over about half a second. It costs a little lag and buys back most of "
                 "the accuracy.",
         plain="'Jitter' is the small random wobble in those dots from frame to frame. The dots are "
               "never perfectly still, so any angle worked out from them wobbles too.",
         notebook="Section 3.1 - elbow angle from three points.",
         takeaway="If a four-millimetre wobble is degrees of elbow angle, the same wobble is a "
                  "large slice of a five-centimetre compression. That is the depth argument, in "
                  "numbers."),

    dict(id="peaks", phase=2, scene="Counting The Pushes", ai="A Hand-Written Peak Finder",
         tech="deeper than both neighbours · past a floor · not too close to the last one",
         site="Everything the unit says is per compression, so before it can say anything it has "
              "to find them.",
         challenge="Pad noise creates hundreds of tiny local maxima, and two candidates a few "
                   "hundredths of a second apart are the same push counted twice.",
         ai_link="Three lines of rule, written out rather than imported, because seeing how "
                 "compressions get counted is half the lesson.",
         plain="A 'peak finder' is a short piece of ordinary code that walks along the signal and marks "
               "every point deeper than both its neighbours. There is no model and no training involved.",
         notebook="Section 4 - counting compressions.",
         takeaway="A peak finder is not machine learning and does not need to be. Reach for the "
                  "simplest thing that answers the question."),

    dict(id="release", phase=2, scene="The Number Between The Peaks", ai="Depth Versus Stroke",
         tech="stroke = how deep it got, minus what it never came back up from",
         site="For every compression the unit also records the shallowest point before the next "
              "one - the depth the helper is still leaning on.",
         challenge="A chest that never comes back up cannot refill with blood, and the depth "
                   "number on its own looks completely fine while that is happening.",
         ai_link="Record two numbers per push instead of one. They are equal only when the "
                 "helper releases fully.",
         plain="'Recoil' is letting the chest come all the way back up between pushes. It sounds like a "
               "detail and it is the difference between the heart refilling and not.",
         notebook="Section 4.1 - full release, and the two columns.",
         takeaway="This one extra column is what makes the next four pages work. Without it, the "
                  "fatigue page has nothing to detect."),

    dict(id="rules", phase=3, scene="One Message At A Time", ai="The Feedback Rules",
         tech="nine rules, ordered by cost to the patient, first one wins",
         site="Hands off centre, too shallow, too deep, leaning, too slow, too fast, bent elbows, "
              "shoulders behind the hands - or a green light.",
         challenge="A frightened untrained helper given four instructions at once follows none "
                   "of them.",
         ai_link="Order the rules by how much each fault costs the patient, and speak only the "
                 "first one that fires. Depth and recoil move blood; a bent elbow only makes the "
                 "helper tire sooner.",
         plain="A 'rule engine' is a checklist tried in a fixed order, where the first match wins. It is "
               "not learned from anything: a clinician decided both the rules and the order.",
         notebook="Section 5 - from measurement to feedback.",
         takeaway="The priority order is the design. Change it and you change what the unit is "
                  "for, without touching a single threshold."),

    dict(id="metronome", phase=3, scene="A Beat To Follow", ai="The Metronome",
         tech="start where the helper is, then walk the beat towards the target",
         site="Told to press faster, a person speeds up briefly and drifts back. Given a beat, "
              "they lock onto it.",
         challenge="A beat that jumps straight to the target is one the helper loses, and a beat "
                   "that follows the helper down out of range is not a reference at all.",
         ai_link="Meet them where they are on the first beat, then move steadily towards the "
                 "middle of the range and never back down out of it.",
         plain="A 'metronome' is the click that sets a tempo, borrowed from music practice. Ours is "
               "adaptive - it starts where the helper already is and walks them to where they should be.",
         notebook="Section 5.1 - the metronome.",
         takeaway="The beat leads and the helper follows. Any version that chases the helper is "
                  "a mirror, not a metronome."),

    dict(id="fatigue", phase=4, scene="The Helper Who Cannot Feel It", ai="Detecting A Trend",
         tech="the stroke, against this helper's own first twenty compressions",
         site="Rescuer A has been going for a minute. They are pressing shallower, drifting "
              "faster, and starting to rest their weight on the chest between pushes.",
         challenge="The obvious detector watches depth falling - and depth barely moves. As the "
                   "helper stops coming all the way up, each push starts from lower down, so the "
                   "chest still reaches roughly the right depth while doing less and less work.",
         ai_link="Detect on the stroke instead, and compare it against this helper's own opening "
                 "compressions rather than an absolute number.",
         plain="A 'trend' is the direction a number is moving over time, as opposed to its value right "
               "now. Someone tiring looks fine on any single push and clearly worse across fifty.",
         notebook="Section 6.1 - is the helper tiring, and the detector that failed first.",
         takeaway="An absolute threshold fires instantly for a small helper and never for a "
                  "strong one. Everybody's baseline is their own."),

    dict(id="switch", phase=4, scene="Time To Swap", ai="The Switch Plan",
         tech="whichever comes first: two minutes, or quality falling",
         site="Guidelines say swap about every two minutes, because quality falls long before "
              "the helper feels tired.",
         challenge="A swap done badly costs ten seconds with nobody's hands on the chest, and "
                   "every one of those seconds is blood not moving.",
         ai_link="Warn the standby person fifteen seconds early so they are already in position, "
                 "and call the swap on whichever trigger arrives first.",
         plain="'Rescuer switching' means swapping the person doing compressions before they tire, "
               "rather than after. The cost is a pause, so when to call it is a genuine trade-off.",
         notebook="Section 6.2 - calling the switch.",
         takeaway="If the helper is alone, the correct output is keep going, do not stop. Telling "
                  "somebody to swap with nobody only tells them they are failing."),

    dict(id="handsoff", phase=4, scene="Hands Off The Chest", ai="Chest Compression Fraction",
         tech="the share of the whole rescue that somebody was actually compressing",
         site="Add up every second nobody's hands were on the chest: the arrival, the AED, the "
              "swap, the pause while somebody fetches something.",
         challenge="Pauses feel short from inside and are never as short as they feel.",
         ai_link="Measure the fraction from the signal itself, without being told where the "
                 "pauses were - because the real unit is not told.",
         plain="'Chest compression fraction' is the share of the whole emergency during which somebody "
               "was actually pushing. Every second nobody is pushing, blood is not moving.",
         notebook="Section 6.3 - hands-off time.",
         takeaway="This is the single number most strongly tied to whether the patient lives. "
                  "Guidelines want at least sixty percent."),

    dict(id="aed", phase=4, scene="The One Decision The AI Must Not Make", ai="Coaching Around The AED",
         tech="four states, and no branch that decides anything about a shock",
         site="While the AED analyses and delivers a shock, nobody may touch the patient. Then "
              "hands go straight back on.",
         challenge="Every extra second after a shock before compressions restart is where "
                   "rescues are lost, and a stunned helper waits for permission.",
         ai_link="Read the AED's state and coach around it. Enforce stand-clear, then say resume "
                 "louder than anything else the unit ever says.",
         plain="An 'AED' is the automatic defibrillator - the box that decides on its own whether a "
               "shock is needed. Our coach must work around it and must never override it.",
         notebook="Section 6.4 - the AED, and the decision the AI must not make.",
         takeaway="Whether to shock belongs to a regulated AED. This state machine has no branch "
                  "that could grow into that decision, and must never be given one."),

    dict(id="timeline", phase=5, scene="The Picture The Paramedic Gets", ai="The Quality Timeline",
         tech="depth, rate, lean, posture and the light bar on one time axis",
         site="The crew arrives. Somebody has to hand over what has been happening for the last "
              "three and a half minutes, and they have about five seconds to do it.",
         challenge="Session averages hide everything. Both rescuers here score about the same "
                   "overall while failing in completely different ways.",
         ai_link="Put every measurement on one shared clock, and colour each compression by what "
                 "the unit said about it.",
         plain="A 'handover' is the moment the paramedic takes charge. Everything on this page exists to "
               "answer their questions in seconds rather than from memory.",
         notebook="Section 7 - the CPR quality timeline.",
         takeaway="The same picture is a handover on arrival and a debrief afterwards. Neither "
                  "is possible from a mean."),

    dict(id="limits", phase=5, scene="What This Would Get Wrong", ai="The Honest List",
         tech="invented data · a fragile camera · thresholds that are not people",
         site="A device that coaches a frightened stranger through the worst minutes of their "
              "life earns a harder look than a demo usually gets.",
         challenge="Everything on these pages came from a generator written by somebody who "
                   "already knew what the analysis should find.",
         ai_link="Say what would break, in order, and be specific enough that somebody could "
                 "test each one.",
         plain="A 'limitation' is something the system genuinely cannot do, written down honestly. The "
               "dangerous version of this app would be one that hid this page.",
         notebook="Section 8 - what this would get wrong, and section 9 - your turn.",
         takeaway="Being told you are failing has a cost. Sometimes the output with the highest "
                  "survival value is keep going, help is coming."),
]

# ------------------------------------------------------- what one push produces
# story.compression_table() emits one row per compression, and the column names
# on that row are the app's real vocabulary: `residual_cm`, `stroke_cm`,
# `hand_cm`. They are shown to students as bare dataframe headers, which teaches
# nobody anything, so each is named here in three parts - the column, what it
# actually is, and what the coach DOES with it.
# The pad and the camera both report 50 times a second.
MEASURE_GROUPS = [
    dict(name="Which push, and when",
         idea="Bookkeeping: enough to put every push in order and attribute it to a person.",
         plan="Never coached on. It is what lets every later chart show change over time "
              "instead of one average that hides everything.",
         rows=[
             ("n", "Which compression this is, counting from 1.",
              "Lets us say 'the 200th push was weaker than the 20th'."),
             ("t", "How many seconds into the emergency this push happened.",
              "The x-axis of every timeline, and how a pause becomes visible."),
             ("rescuer", "Which of the two helpers was pushing, A or B.",
              "Fatigue is per person, so nothing about tiring works without this."),
         ]),
    dict(name="How far the chest moved",
         idea="Three numbers from the same push: the bottom, the top, and the distance between.",
         plan="The heart of the whole app. Depth alone looks fine while the chest is never "
              "allowed back up, and the gap between depth and stroke is what exposes that.",
         rows=[
             ("depth_cm", "How far down the chest got at the bottom of the push.",
              "Compared against the 5-6 cm guideline: too little moves no blood, too much injures."),
             ("residual_cm", "How far down the chest still is at the *top* of the release.",
              "Should be near zero. Anything above 0.5 cm means the chest never came back up."),
             ("stroke_cm", "Depth minus residual - how far the chest actually travelled.",
              "The honest measure of work done. It is the number that falls first as a helper tires."),
         ]),
    dict(name="How fast",
         idea="The gap to the next push, turned into pushes per minute.",
         plan="Drives the metronome. Note it is measured from the gap, so the last push before "
              "a pause has no rate at all rather than a very slow one.",
         rows=[
             ("rate_cpm", "Pushes per minute, worked out from the gap to the next push.",
              "Kept between 100 and 120: slower moves too little blood, faster gets shallower."),
         ]),
    dict(name="What the body is doing",
         idea="Three positions read off the camera's keypoints at the moment of the push.",
         plan="These change *how long the helper lasts* rather than how good one push is - "
              "which is exactly why they rank below depth in the coaching order.",
         rows=[
             ("elbow_deg", "The angle at the elbow; 180 degrees is a straight arm.",
              "Bent arms mean the arms are doing work the body weight should do, so the helper tires."),
             ("shoulder_cm", "How far the shoulders sit behind the hands.",
              "Being over the hands is what lets body weight, not muscle, do the pushing."),
             ("hand_cm", "How far the hands are from the centre of the breastbone.",
              "The one position fault ranked top: off-centre, the push lands on ribs."),
         ]),
]

MEASURE_COUNT = sum(len(g["rows"]) for g in MEASURE_GROUPS)

# Friendly headers for the one dataframe that shows raw column names to students.
MEASURE_LABELS = {
    "depth_cm": "Depth (cm)",
    "stroke_cm": "Actual travel (cm)",
    "residual_cm": "Still pressed in (cm)",
    "rate_cpm": "Rate (per min)",
    "elbow_deg": "Elbow angle (deg)",
}


BY_ID = {s["id"]: s for s in STEPS}
ORDER = [s["id"] for s in STEPS]
