"""Shared teaching registry for the notebook and illustration app."""
PHASES=[("The daily gamble","Production happens before demand is known."),("Learn the demand","Price, time and context move sales."),
        ("Rescue the surplus","Evaluate actions, production and donation together."),("Prove the policy","Test shocks, fairness and seven days.")]
STEPS=[
dict(id="morning",phase=0,scene="Monday Morning At The Bakery",ai="Inventory Becomes A Decision Problem",tech="five products · price · cost · shelf life · opening stock",site="Bread, croissants, sandwiches, cake slices and savoury rolls are prepared before exact demand is known.",challenge="Too little loses customers. Too much turns ingredients, labour and energy into closing waste.",ai_link="The simulation keeps financial, operating and waste accounts for every product and hour.",notebook="Phases 1–3: products, customers and the fixed-price baseline.",takeaway="Unsold food is both an inventory error and a social loss."),
dict(id="demand",phase=1,scene="Customers Do Not Arrive Evenly",ai="Demand Curves And Forecasts",tech="hour · weekday · weather · event · footfall · popularity",site="Morning bread, lunch sandwiches and evening pastries follow different rhythms.",challenge="Rain can empty the shop while a nearby event can reverse the forecast within an hour.",ai_link="Models forecast the next hour and the whole safe selling window, with bias reported beside MAE.",notebook="Phases 2 and 6–8: demand, dataset and forecasts.",takeaway="The useful forecast ends at the safe-sale deadline, not at closing."),
dict(id="price",phase=1,scene="A Discount Changes Demand",ai="Price Elasticity",tech="D(p)=D₀(p/p₀)^−ε",site="Staple bread and evening sandwiches do not respond equally to the same price cut.",challenge="A universal closing discount gives margin away on products that would have sold anyway.",ai_link="Product-specific elasticity turns each public price into a transparent demand multiplier.",notebook="Phases 4–5: closing discount and elasticity.",takeaway="Discount timing matters as much as discount size."),
dict(id="actions",phase=2,scene="Sell, Bundle, Promote Or Reserve",ai="Action Simulation",tech="profit · waste · donation · customers · lost sales",site="At 5 PM, 38 sandwiches remain and rain has reduced footfall. A shelter can collect at 7:15 PM.",challenge="The action with the highest immediate revenue may leave unusable stock or no collection time.",ai_link="Every feasible action is simulated against the same forecast before one is recommended.",notebook="Phases 9–10: rules and action evaluation.",takeaway="Compare complete consequences, not just the price on the label."),
dict(id="objective",phase=2,scene="Whose Definition Of Best?",ai="Multi-Objective Optimization",tech="profit − waste + donation + customers − lost sales",site="The owner, operations team and community partner value different outcomes.",challenge="One hidden set of weights turns a business judgment into an unexplained algorithmic fact.",ai_link="Students move between profit-first, waste-first, balanced and community-first policies.",notebook="Phase 11: multi-objective optimization.",takeaway="AI weights are business values written as numbers."),
dict(id="donation",phase=2,scene="Donation Needs A Clock",ai="Shelter Logistics",tech="capacity · products · pickup · remaining safe life · transport",site="Usable surplus must reach a shelter while it is still suitable and while collection is possible.",challenge="Waiting until closing can make a generous plan physically impossible.",ai_link="The controller reserves stock early and protects a promised donation from a tiny late profit opportunity.",notebook="Phase 12: donation logistics.",takeaway="Donation is inventory planning, not disposal with better language."),
dict(id="production",phase=2,scene="Should We Bake Another Batch?",ai="Marginal Contribution",tech="incremental revenue − batch cost − expected waste",site="A second batch can meet an evening rush—or become tomorrow's disposal cost.",challenge="Average profit from the morning says little about the next batch at 4 PM.",ai_link="The controller evaluates full, half, delayed and stopped production using incremental contribution.",notebook="Phase 13: stop-production decision.",takeaway="Sunk morning costs do not justify another avoidable batch."),
dict(id="behaviour",phase=3,scene="Do Not Train Everyone To Wait",ai="Customer Behaviour And Fairness",tech="one public price · deep-discount frequency cap · truthful reference price",site="Some customers buy now, some seek bundles and some learn to wait for the final discount.",challenge="Frequent predictable price drops can weaken margin and trust even if today's waste falls.",ai_link="Policy constraints limit deep discounts and prohibit identity-based prices or misleading scarcity.",notebook="Phase 14: customer behaviour.",takeaway="The same period has one truthful public price for everyone."),
dict(id="shocks",phase=3,scene="The Forecast Is Allowed To Be Wrong",ai="Event Replanning",tech="rain · event · failed refrigerator · cancelled shelter · sensor loss",site="Rain intensifies, a school group arrives or the shelter cancels its collection.",challenge="A good earlier plan may become unsafe, wasteful or impossible after new evidence.",ai_link="The controller recomputes, but hard promises and food-safety limits remain fixed.",notebook="Phase 15: unexpected events.",takeaway="Revise the forecast; do not revise the ethical boundary."),
dict(id="week",phase=3,scene="Seven Days, One Honest Ledger",ai="Strategy Benchmark",tech="revenue · contribution · discarded · donated · served",site="Fixed price, closing discount and balanced control face the same simulated week.",challenge="A single-day success can hide repeated discounting, stockouts or donation failures.",ai_link="The final ledger separates accounting, operating, environmental and fairness measures.",notebook="Phase 16: control room and seven-day benchmark.",takeaway="The strongest strategy survives both the ledger and the waste bin."),]
BY_ID={s["id"]:s for s in STEPS};ORDER=[s["id"] for s in STEPS]
