import * as THREE from './three.mjs';
import {OrbitControls} from './controls.mjs';
import {GLTFLoader} from './loader.mjs';
const $=id=>document.getElementById(id),stage=$('stage');
const send=(type,data)=>parent.postMessage({isStreamlitMessage:true,type,...data},'*');
let topics=[],selected='cpu',hovered=null,model=null,labelsOn=true;
const meshes=[],groups=new Map(),tags=new Map(),buttons=new Map();
const leaders=document.createElementNS('http://www.w3.org/2000/svg','svg');leaders.style.cssText='position:absolute;inset:0;width:100%;height:100%;pointer-events:none';$('labels').prepend(leaders);const lines=new Map();
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(42,1,.001,200);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;
stage.prepend(renderer.domElement);renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','Interactive server model. Drag to rotate. Scroll or pinch to zoom.');
scene.add(new THREE.HemisphereLight(0xcdeeff,0x71849c,2.8));
for(const [pos,power] of [[[4,7,5],4],[[-4,3,-3],3],[[0,-5,3],2]]){const l=new THREE.DirectionalLight(0xffffff,power);l.position.set(...pos);scene.add(l);}
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=false;controls.minPolarAngle=.01;controls.maxPolarAngle=Math.PI-.01;controls.autoRotate=false;controls.zoomSpeed=3.5;controls.zoomToCursor=true;controls.minDistance=.015;controls.maxDistance=35;
const raycaster=new THREE.Raycaster(),mouse=new THREE.Vector2();
let fullBox=new THREE.Box3(),fullCenter=new THREE.Vector3(),fullSize=5;
function fit(box){if(box.isEmpty())return;const center=box.getCenter(new THREE.Vector3()),size=Math.max(...box.getSize(new THREE.Vector3()).toArray());controls.target.copy(center);camera.position.copy(center).add(new THREE.Vector3(.85,.9,1.2).normalize().multiplyScalar(size*1.8));controls.update();}
function reset(){fit(fullBox);}
async function toggleFullscreen(){
 try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}
 catch(error){$('status').textContent='Full screen is blocked by this browser. Open the app in Chrome or Edge and try again.';}
}
document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent=document.fullscreenElement?'Exit full screen':'Full screen';resize();});
function highlight(){for(const mesh of meshes){const active=mesh.userData.lesson===hovered,chosen=mesh.userData.lesson===selected;for(const m of (Array.isArray(mesh.material)?mesh.material:[mesh.material])){if(m.emissive){m.emissive.copy(m.userData.baseEmissive);if(active||chosen)m.emissive.lerp(new THREE.Color(active?0x21bee8:0x146276),active?.55:.22);}}}for(const [id,b]of buttons)b.classList.toggle('active',id===selected);for(const[id,b]of tags)b.classList.toggle('active',id===selected);}
function hover(id){if(hovered===id)return;hovered=id;highlight();const t=topics.find(t=>t.id===id);$('tip').replaceChildren();$('tip').style.display=t?'block':'none';if(t){const b=document.createElement('b');b.textContent=t.title;$('tip').append(b,document.createTextNode(t.summary));}}
function select(id,notify=true){selected=id;highlight();if(notify)send('streamlit:setComponentValue',{value:{topic_id:id,event_id:crypto.randomUUID()},dataType:'json'});}
function populate(){if(buttons.size)return;for(const t of topics){const b=document.createElement('button');b.innerHTML=`<span>${String(t.number).padStart(2,'0')}</span>`;b.append(document.createTextNode(t.title));b.onclick=()=>select(t.id);b.onmouseenter=()=>hover(t.id);b.onmouseleave=()=>hover(null);$('topics').append(b);buttons.set(t.id,b);const tag=document.createElement('button');tag.className='tag';tag.textContent=`${t.number} ${t.title}`;tag.onclick=()=>select(t.id);tag.onmouseenter=()=>hover(t.id);tag.onmouseleave=()=>hover(null);$('labels').append(tag);tags.set(t.id,tag);}highlight();resize();}
function resize(){const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();if(!document.fullscreenElement)send('streamlit:setFrameHeight',{height:document.body.scrollHeight});}
new ResizeObserver(resize).observe(stage);
$('reset').onclick=reset;$('focus').onclick=()=>{const box=new THREE.Box3();for(const m of groups.get(selected)||[])box.expandByObject(m);fit(box);};$('labelsToggle').onclick=()=>{labelsOn=!labelsOn;$('labels').style.display=labelsOn?'block':'none';$('labelsToggle').textContent=`Labels: ${labelsOn?'on':'off'}`;};$('fullscreen').onclick=toggleFullscreen;
function pick(e){const r=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(mouse,camera);return raycaster.intersectObjects(meshes,false)[0]?.object.userData.lesson;}
renderer.domElement.addEventListener('pointermove',e=>{if(!e.buttons)hover(pick(e)||null);});renderer.domElement.addEventListener('pointerleave',()=>hover(null));
let down=null;renderer.domElement.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY];renderer.domElement.focus();});renderer.domElement.addEventListener('pointerup',e=>{if(down&&Math.hypot(e.clientX-down[0],e.clientY-down[1])<5){const id=pick(e);if(id)select(id);}down=null;});
window.addEventListener('message',e=>{if(e.source!==parent||e.data.type!=='streamlit:render')return;topics=e.data.args.topics||[];selected=e.data.args.selected||selected;populate();highlight();});
send('streamlit:componentReady',{apiVersion:1});resize();
new GLTFLoader().load('./model.glb',g=>{model=g.scene;scene.add(model);model.updateMatrixWorld(true);model.traverse(o=>{if(/^(TOPIC|Topic_leader|Topic_marker|Label_backing|Lesson_heading|Lesson_note|Scale_note)/.test(o.name))o.visible=false;});model.traverse(o=>{if(!o.isMesh)return;let p=o,id=null,visible=true;while(p){if(!p.visible)visible=false;if(!id&&p.userData.topic_id)id=p.userData.topic_id;p=p.parent;}if(!visible)return;fullBox.expandByObject(o);if(!id)return;o.userData.lesson=id;o.material=Array.isArray(o.material)?o.material.map(m=>m.clone()):o.material.clone();for(const m of(Array.isArray(o.material)?o.material:[o.material]))m.userData.baseEmissive=m.emissive?.clone();meshes.push(o);if(!groups.has(id))groups.set(id,[]);groups.get(id).push(o);});fullCenter=fullBox.getCenter(new THREE.Vector3());fullSize=fullBox.getSize(new THREE.Vector3()).length();reset();highlight();$('loading').style.display='none';window.serverExplorer={get ready(){return true},get selected(){return selected},get topics(){return [...groups.keys()]},get meshCount(){return meshes.length}};},undefined,()=>{$('loading').textContent='The model could not load. Restart the app and reload this page.';});
function animate(){requestAnimationFrame(animate);controls.update();if(model&&labelsOn){const placed=[];for(const t of topics){const tag=tags.get(t.id);if(!tag)continue;let line=lines.get(t.id);if(!line){line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('stroke','#73c9dd');line.setAttribute('stroke-opacity','.6');leaders.append(line);lines.set(t.id,line);}const[x,y,z]=t.anchor_blender,p=new THREE.Vector3(x,z,-y).project(camera);const visible=p.z<=1&&p.z>=-1&&Math.abs(p.x)<1.1&&Math.abs(p.y)<1.1;tag.style.visibility=visible?'visible':'hidden';line.style.display=visible?'':'none';if(!visible)continue;const ax=(p.x+1)*stage.clientWidth/2,ay=(1-p.y)*stage.clientHeight/2;let px=Math.max(80,Math.min(stage.clientWidth-80,ax)),py=Math.max(15,Math.min(stage.clientHeight-15,ay));for(let n=0;n<18&&placed.some(q=>Math.abs(q[0]-px)<155&&Math.abs(q[1]-py)<24);n++)py=py-25<15?stage.clientHeight-15:py-25;placed.push([px,py]);tag.style.left=px+'px';tag.style.top=py+'px';line.setAttribute('x1',ax);line.setAttribute('y1',ay);line.setAttribute('x2',px);line.setAttribute('y2',py);}}renderer.render(scene,camera);}animate();
