PHASES=[("The Budget Dilemma","Damage exceeds the money available for repair."),("Defining Public Benefit","Five road attributes become a transparent planning target."),("Learning Priority","An MLP estimates benefit from road characteristics."),("Selecting the Programme","Knapsack optimization chooses an affordable portfolio."),("Comparing Policies","Optimized selection is tested against simple ranking rules."),("Decision Audit","Equity, uncertainty, and governance limits are explicit.")]
STEPS=[
dict(id="problem",phase=0,civil="More Damaged Roads Than Budget",ai="Resource-Constrained Decision",tech="which repairs maximize network benefit?",site="A city maintains many damaged roads but cannot fund every treatment in the current programme.",challenge="Repairing only the worst pavement can consume the budget while leaving high-traffic, safety-critical links untreated.",ai_link="Estimate each road's public benefit and select the combination with the greatest total benefit under the budget.",notebook="Define ranking and portfolio selection as separate tasks.",takeaway="The best individual road and the best affordable programme are different questions."),
dict(id="inputs",phase=0,civil="Five Road Planning Attributes",ai="Ranking Features",tech="condition, traffic, cost, accident risk, importance",site="Each candidate has a condition score, daily traffic, repair cost, accident risk, and strategic importance.",challenge="The inputs use different units, and cost affects affordability while the other attributes largely describe benefit.",ai_link="Keep five named inputs, but audit whether cost should influence ranking or only the downstream budget optimizer.",notebook="Create the road table and inspect physical/planning ranges.",takeaway="Feature roles must be defined before training: benefit evidence is not identical to budget cost."),
dict(id="benefit",phase=1,civil="What Counts as Maintenance Benefit?",ai="Supervised Ranking Target",tech="weighted damage + traffic + risk + importance",site="A planning policy must state how pavement distress, usage, safety, and critical connections contribute to benefit.",challenge="Hidden or arbitrary weights can turn an AI score into an unreviewable policy decision.",ai_link="Generate a transparent educational benefit target with declared weights and noise, then let the MLP learn its combined pattern.",notebook="Calculate normalized component benefits and the training target.",takeaway="The model learns the policy encoded in its labels; it does not discover public values independently."),
dict(id="data",phase=1,civil="A Municipal Road Candidate List",ai="Synthetic Training Dataset",tech="hundreds of roads and plausible correlations",site="Road condition, traffic, risk, importance, and treatment cost vary across a municipal network.",challenge="Random independent columns miss realistic relationships such as more extensive damage generally costing more to repair.",ai_link="Generate overlapping, correlated road records and reserve a separate current-year programme for optimization.",notebook="Build training roads and a named 20-road planning list.",takeaway="Synthetic data demonstrates method, not a real authority's priorities."),
dict(id="prepare",phase=2,civil="Putting Road Records on One Scale",ai="Normalization",tech="training-only imputer and StandardScaler",site="Traffic may be tens of thousands of vehicles while risk and importance use small ordinal scales.",challenge="Raw magnitude distorts MLP training, and full-dataset scaling leaks test information.",ai_link="Split first, then learn imputation and scaling parameters from training records only.",notebook="Prepare five features without leakage.",takeaway="Preprocessing is part of the ranking model and must be reproduced during planning."),
dict(id="ranking",phase=2,civil="Estimating Maintenance Priority",ai="MLP Ranking Model",tech="5 -> Dense32 -> Dense16 -> priority score",site="Engineers need comparable road-level benefit estimates before assembling a programme.",challenge="A score order alone ignores budget interactions and can favour expensive roads that crowd out a better combination.",ai_link="Train a compact MLP to estimate priority benefit, then pass predictions—not ranks—to the optimizer.",notebook="Train the regression MLP and score the current programme roads.",takeaway="Ranking estimates individual value; optimization decides collective selection."),
dict(id="rank_audit",phase=2,civil="Checking the Priority Scores",ai="Ranking Evaluation",tech="MAE, Spearman correlation, top-k overlap",site="Planning quality depends on preserving the relative order of high-benefit roads, not only predicting exact score values.",challenge="Low MAE can coexist with poor ordering near the funding cutoff.",ai_link="Audit numeric error, rank correlation, and top-k overlap, especially for safety-critical roads.",notebook="Evaluate unseen-road scores and inspect large ranking disagreements.",takeaway="A ranking model should be evaluated as a ranking model."),
dict(id="budget",phase=3,civil="Choosing the Affordable Portfolio",ai="0/1 Knapsack Optimization",tech="maximize predicted benefit subject to total cost ≤ budget",site="Each road is either funded this programme or deferred, and the total treatment cost cannot exceed the approved budget.",challenge="Selecting in score order can leave unusable budget or miss a combination with greater total benefit.",ai_link="Use exact dynamic programming at ₹1-lakh resolution to find the highest predicted-benefit combination.",notebook="Run knapsack and produce selected/deferred lists and budget use.",takeaway="The optimizer chooses combinations; a sorted list does not."),
dict(id="compare",phase=4,civil="The Maintenance Programme Audit",ai="Policy Comparison and Governance",tech="worst-first vs score-first vs optimized",site="Decision-makers need to see what improved, who was deferred, and how sensitive the plan is to budget and policy weights.",challenge="A numerically optimal programme can still conflict with statutory duties, geographic equity, emergency routes, or minimum service obligations.",ai_link="Compare policies, vary budget, report uncertainty, and keep final approval with accountable planners.",notebook="Show schedule, cost, benefit, sensitivity, and limitations.",takeaway="Optimization supports a transparent programme; it does not replace public-sector governance.")]
BY_ID={s["id"]:s for s in STEPS};ORDER=[s["id"] for s in STEPS]

