PHASES=[("The Storage Dilemma","Too little storage wastes rainfall; too much wastes money and space."),("Building Water Evidence","A daily water-balance simulation creates honest training targets."),("Learning Utilization","An MLP surrogate estimates annual useful supply for candidate tanks."),("Optimizing the Design","Cost, shortage, overflow, and diminishing returns guide tank selection."),("Selecting and Reviewing","A system type is recommended with explicit limitations.")]
STEPS=[
dict(id="problem",phase=0,civil="The Rainwater Storage Decision",ai="Recommendation and Optimization",tech="useful supply versus cost, shortage, and overflow",site="A harvesting design must collect useful roof runoff without oversizing storage.",challenge="A small tank overflows and misses demand; a large tank costs more and may add little benefit.",ai_link="Predict utilization for candidate capacities, then optimize a declared engineering objective.",notebook="Separate water-yield prediction from tank and system selection.",takeaway="Maximum tank size is not automatically the best design."),
dict(id="inputs",phase=0,civil="Six Design Inputs",ai="Tabular Features",tech="area, rainfall, demand, runoff, cost, available capacity",site="The site is represented by roof area, annual rainfall, daily non-potable demand, runoff coefficient, tank cost, and maximum installation capacity.",challenge="Annual rainfall volume alone ignores timing, consumption, storage cycling, cost, and space.",ai_link="Keep the six inputs interpretable and add candidate capacity when evaluating alternatives.",notebook="Create and inspect the required site inputs.",takeaway="Storage design depends on both annual volume and daily timing."),
dict(id="balance",phase=1,civil="Daily Tank Water Balance",ai="Simulation Target",tech="inflow, demand, storage, overflow, shortage",site="Rain enters the tank on wet days, demand removes water daily, and excess above capacity becomes overflow.",challenge="Theoretical annual collection does not reveal how much water can actually be used.",ai_link="Simulate daily rainfall and tank operation to calculate annual supplied water, overflow, and shortage.",notebook="Implement the physical water-balance target generator.",takeaway="Useful supply is constrained by rainfall timing, storage, and demand."),
dict(id="data",phase=1,civil="Simulated Harvesting Designs",ai="Synthetic Training Dataset",tech="thousands of sites and candidate capacities",site="Training cases span climate, roof, demand, runoff, cost, and tank-size combinations.",challenge="A surrogate trained on narrow cases will extrapolate poorly to new sites.",ai_link="Sample broad plausible ranges and reserve unseen site-capacity combinations for testing.",notebook="Generate simulated utilization examples and audit ranges.",takeaway="Synthetic results teach method; local rainfall records are required for real design."),
dict(id="prepare",phase=2,civil="Preparing Design Variables",ai="Leakage-Safe Scaling",tech="split first, fit scaler on training data",site="Input magnitudes range from coefficients below one to capacities of many thousands of litres.",challenge="Raw scales destabilize training and full-dataset scaling leaks test information.",ai_link="Split first and standardize with training-only statistics.",notebook="Prepare seven MLP inputs including candidate tank capacity.",takeaway="The same scaler must be used for every optimized candidate."),
dict(id="model",phase=2,civil="Estimating Useful Rainwater",ai="MLP Regression",tech="7 -> Dense64 -> Dense32 -> annual supply",site="The optimizer needs a fast estimate for many possible tank capacities.",challenge="Repeated full simulation can become expensive across many sites and scenarios.",ai_link="Train an MLP surrogate to estimate annual useful water supplied.",notebook="Train with early stopping and inspect learning curves.",takeaway="The MLP approximates the simulator; it does not replace hydrologic evidence."),
dict(id="audit",phase=2,civil="Checking the Utilization Model",ai="Regression Audit",tech="MAE, R², residuals, physical clipping",site="Prediction errors affect demand coverage and the selected tank size.",challenge="A good average score can hide bias for small tanks, dry climates, or high-demand sites.",ai_link="Audit held-out errors and clip predictions to physical limits.",notebook="Evaluate predictions and examine residuals by capacity.",takeaway="Optimization is only as trustworthy as the surrogate in the candidate region."),
dict(id="optimize",phase=3,civil="Choosing Tank Capacity",ai="Candidate Optimization",tech="shortage + overflow + cost + diminishing returns",site="Feasible tank capacities are limited by installation space and budget.",challenge="Weights and cost assumptions determine whether water savings justify extra storage.",ai_link="Score every feasible candidate and show the full trade-off table rather than only the winner.",notebook="Optimize capacity and visualize the elbow in benefit versus cost.",takeaway="The recommended capacity is conditional on declared weights and candidate steps."),
dict(id="system",phase=4,civil="System Type and Design Review",ai="Interpretable Recommendation Layer",tech="rooftop, modular, underground, or storage + recharge",site="Tank capacity, surface space, rainfall, and overflow opportunity influence the system arrangement.",challenge="System choice also requires ground conditions, water quality, mosquito control, first-flush, filtration, structural access, codes, and maintenance planning.",ai_link="Apply transparent conditions, explain the reason, test sensitivity, and require professional approval.",notebook="Produce the final system, capacity, metrics, reasons, and limitations.",takeaway="The output is a preliminary concept recommendation, not construction-ready design.")]
BY_ID={s["id"]:s for s in STEPS};ORDER=[s["id"] for s in STEPS]
