"""One five-part teaching card for each illustration page."""
PHASES = [
    ("The road wakes up", "Observe before deciding."),
    ("Make space", "Physics sets the floor; AI adapts above it."),
    ("Protect access", "Manage drivers, helpers and responders together."),
    ("Prove and recover", "Fail safely, measure honestly, reopen slowly."),
]
STEPS = [
 dict(id="scene",phase=0,scene="A Rider In The Centre Lane",ai="The Road Becomes The Safety System",tech="three lanes · cameras · radar · connected studs",site="A motorcycle falls in the centre lane on a wet road. Traffic is still arriving at 72 km/h.",challenge="The closest driver has only distance, friction and reaction time between an ordinary stop and a second collision.",ai_link="The edge computer converts the same road observations into one protected traffic plan.",notebook="Phases 1–3: build the road, normal traffic and the incident.",takeaway="Protect the scene before asking anybody to approach it."),
 dict(id="detect",phase=0,scene="One Shape, Several Explanations",ai="Temporal Incident Detection",tech="persistence · orientation · separation · trajectory change",site="A low shape in a lane may be a rider, debris, a worker, a crossing pedestrian or a shadow.",challenge="One frame has no before and after. Noise and occlusion can erase the most useful clue.",ai_link="The detector combines several seconds of weak signals and reports uncertainty without diagnosing injury.",notebook="Phase 4: compare a frame, temporal rules, a forest and a sequence model.",takeaway="Detect an obstruction over time; never infer a medical condition."),
 dict(id="distance",phase=1,scene="How Much Road Is Enough?",ai="Physics-Guided Warning Distance",tech="reaction + braking + uncertainty margin",site="At 72 km/h the vehicle travels metres while the driver is only beginning to react.",challenge="Speed, wet friction, vehicle mass, visibility, slope and driver delay all move the safe boundary.",ai_link="Physics supplies a minimum. A learned residual accounts for interactions and uncertainty above it.",notebook="Phases 5–8: stopping distance, fixed warning, prediction and asymmetric loss.",takeaway="AI may add margin; it may not negotiate below the physical minimum."),
 dict(id="zones",phase=1,scene="A Warning That Changes Shape",ai="Connected Road-Stud Controller",tech="awareness → slow → merge → exclude",site="Drivers need a gradual sequence, not a red wall that appears beside the rider.",challenge="The pattern must expand as speed or uncertainty rises and contract when it is safe.",ai_link="The controller turns one warning distance into five legible zones and a temporary speed limit.",notebook="Phase 9: connected road-stud zones and live road state.",takeaway="Warn early, slow gradually, close locally."),
 dict(id="merge",phase=2,scene="Centre Closed Does Not Mean Left",ai="Capacity-Aware Merge Choice",tech="lane occupancy · gaps · ramps · ambulance priority",site="The left lane is available. The right lane is congested. An ambulance will need a clear approach.",challenge="Moving every vehicle into the wrong lane creates harsh braking and can block the responder route.",ai_link="A constrained score selects left, right, split or a temporary full stop.",notebook="Phases 10–12: driver response, merge choice and ambulance access.",takeaway="The safest receiving lane is a state, not a rule."),
 dict(id="routes",phase=2,scene="A Safe Way For People And Responders",ai="Risk-Aware Path Planning",tech="Dijkstra cost map · active lanes carry a large penalty",site="A helper is on the shoulder and the rider is in the centre lane. The shortest line crosses moving traffic.",challenge="A route is safe only after the traffic protection that makes it safe is confirmed.",ai_link="The planner treats moving lanes, the exclusion zone and ambulance lane as costs and constraints.",notebook="Phase 13: protected bystander and ambulance routes.",takeaway="Never draw a green path through an active lane."),
 dict(id="failure",phase=3,scene="When The Road Cannot Trust Its Senses",ai="Conservative Fallback",tech="redundancy · confidence gates · fail-safe stop",site="Rain hides the camera, radar drops out, and several studs fail to acknowledge.",challenge="An optimizer can become dangerously precise when its inputs are wrong.",ai_link="Confidence gates bypass optimization, expand the warning and ask traffic control to stop entries.",notebook="Phase 14: hazards and sensor failures.",takeaway="Uncertainty should make the protected zone larger, not the claim louder."),
 dict(id="score",phase=3,scene="Did The Shield Help?",ai="Controller Benchmark",tech="risk · braking · delay · blockage",site="The same synthetic incident is replayed under seven controllers.",challenge="A controller can reduce delay by quietly accepting more collision risk.",ai_link="The benchmark gives secondary collision the dominant penalty and reports each cost separately.",notebook="Experiments, success metrics and final dashboard.",takeaway="Never hide safety behind an average score."),
 dict(id="restore",phase=3,scene="Opening The Road Is Also A Safety Action",ai="Staged Restoration",tech="verify → shrink → release → record",site="Responders clear the centre lane, but drivers still expect an obstruction and queues remain compressed.",challenge="Instantly returning every signal and speed limit to normal can create one final conflict.",ai_link="A guarded state machine keeps a reduced speed, releases traffic gradually and records failed hardware.",notebook="Phase 15: restore normal traffic.",takeaway="The incident ends when the road is stable, not when the rider leaves."),
]
BY_ID={s["id"]:s for s in STEPS}
ORDER=[s["id"] for s in STEPS]
