"""The 13 core lessons and the content grounding the tutor."""

LESSONS = [
 dict(id='server_purpose', title='Server Purpose', kicker='Start with the service',
 summary='A server provides shared services to other computers, called clients.',
 body='A client sends a request across a network. Server software receives it, performs the requested work, and sends a response. A server might deliver a website, keep shared files, run a database, check a login, or execute a computation.\n\nThe word server can describe the software role or the computer running that software. A powerful computer is not automatically a server: what matters is that it provides a service. One physical server can run multiple services, and a large service can use many servers.',
 points=[('Client','The device or program asking for a service.'),('Request','A message asking the service to do something.'),('Response','The result or status returned to the client.')],
 flow=['Client request','Network','Server service','Response'],
 example='A student opens a class timetable. The browser requests the page, the school server retrieves the timetable, and the browser displays the response.',
 analogy='A library desk serves many readers: each reader asks for information and the desk returns the appropriate result.',
 misconception='A server is not necessarily a large rack. A laptop can act as a server, although dedicated hardware is often chosen for reliability and capacity.',
 activity=('Which service would help a team share documents?', ['File service','Video display brightness','Keyboard lighting'], 0, 'A file service stores shared documents and controls how clients access them.'),
 quiz=('In the timetable example, which item is the client?', ['The student’s browser','The timetable database','The server power supply'], 0, 'The browser requests the service, so it is the client.'),
 spot='Find the client screens and the network connections on the left of the complete model.'),
 dict(id='server_architecture',title='Server Architecture',kicker='See how the system works together',
 summary='Server architecture describes how hardware and software cooperate to deliver a service.',
 body='At the hardware level, processors execute instructions, RAM holds working data, storage keeps persistent data, and network interfaces carry requests and responses. The motherboard supplies the sockets, buses and connections that link these parts. A bus is a communication path between components.\n\nAt the software level, an operating system manages resources and applications provide services. Virtual machines can share one physical server through a hypervisor. The exact data path depends on the workload: cached data may already be in RAM, so every request does not require a storage read.',
 points=[('Compute','CPU and optional accelerators do the processing.'),('Memory and storage','RAM holds active data; drives retain data.'),('I/O','Input/output connects the server to networks and devices.')],
 flow=['Network request','Application + CPU','RAM / storage','Network response'],
 example='A web application receives an order, checks data in memory or a database, performs calculations, and sends confirmation.',
 analogy='A workshop needs workers, workbenches, a storeroom and delivery routes. Its layout affects how well work moves between them.',
 misconception='The architecture board in the 3D model is a conceptual diagram, not an extra physical circuit board inside the server.',
 activity=('A frequently requested result is already cached in RAM. Must the server always read a drive?', ['No, it can use the cached data','Yes, every request reads every drive','Only if the keyboard is connected'],0,'Caching lets a service reuse data already in memory, although correctness rules still apply.'),
 quiz=('Which pair separates temporary working data from persistent data?', ['RAM and storage','NIC and Ethernet cable','Fan and heatsink'],0,'RAM is working memory; storage retains data across power loss.'),
 spot='The colored architecture blocks show compute, memory, storage and network I/O in the same 3D setup.'),
 dict(id='rack_servers',title='Rack Servers',kicker='A standardized place for many machines',
 summary='Rack servers are horizontal enclosures designed to mount in equipment racks.',
 body='A rack organizes servers using mounting rails. Rack height is measured in units called U; one U is 1.75 inches (44.45 mm). A 1U or 2U server occupies one or two of those vertical units. Width, depth, rail compatibility, weight, airflow and service access also matter.\n\nEach rack server normally has its own processors, memory, network interfaces and power supplies. A cabinet can hold several independent servers, switches and power equipment. Front-to-rear cooling is common, but real layouts must be checked for the equipment being installed.',
 points=[('U','A unit of rack mounting height.'),('Rails','Support the chassis and can allow it to slide out for service.'),('Density','Several independent servers fit in an organized space.')],
 flow=['Rack rails','Server chassis','Power + network','Shared service'],
 example='A school IT room places several application and storage servers in one cabinet instead of distributing tower cases across desks.',
 analogy='Like standardized shelves holding separate appliances: the shelf organizes them, but each appliance still has its own working parts.',
 misconception='A rack cabinet is not one giant CPU. The horizontal servers inside it can be independent computers.',
 activity=('Which deployment benefits most from a rack?', ['Many servers in an equipment room','One tablet carried between classes','A keyboard with no computer'],0,'A rack organizes multiple devices, cabling and maintenance access.'),
 quiz=('What does 2U describe?', ['Two units of rack height','Two CPU cores','Two network ports'],0,'U is a mounting-height measurement, not a processing specification.'),
 spot='Find the tall cabinet and the horizontal server trays at the back-left. The open server at the front is also a rack server.'),
 dict(id='blade_servers',title='Blade Servers',kicker='Compute modules in a shared enclosure',
 summary='A blade server is a removable compute module that operates inside a compatible enclosure.',
 body='Each compute blade contains processors and memory, often with local storage or storage connections. The enclosure supplies shared infrastructure such as power, cooling, networking and management. A midplane or backplane provides internal connections.\n\nThis can pack compute capacity into a compact space and centralize management. The tradeoff is dependence on the enclosure design and its shared resources. A blade is not normally used on its own like a tower, and compatibility is specific to an enclosure family.',
 points=[('Compute blade','A removable module with processing and memory.'),('Enclosure','Provides shared infrastructure for its blades.'),('Midplane','Connects modules to power and data paths.')],
 flow=['Shared enclosure','Compute blade','Internal interconnect','Network / storage'],
 example='An organization adds compatible compute blades to an existing enclosure as demand grows, after checking power and cooling capacity.',
 analogy='Several workstations in one building share utilities, even though each workstation performs its own work.',
 misconception='A blade is not just a thinner rack server with all the same independent facilities. It relies on an enclosure.',
 activity=('What must be checked before adding a blade?', ['Enclosure compatibility and capacity','Only the case color','Only the monitor size'],0,'The enclosure must support that blade and have enough power, cooling and connectivity.'),
 quiz=('Which resources are commonly shared by blades?', ['Enclosure power and cooling','One mandatory shared CPU','A single keyboard instruction'],0,'Blades usually have their own processors while sharing enclosure infrastructure.'),
 spot='Find the enclosure with narrow vertical modules at the back-center. One blade is partially pulled out.'),
 dict(id='tower_servers',title='Tower Servers',kicker='A server that stands on its own',
 summary='A tower server uses a freestanding upright cabinet rather than requiring rack rails.',
 body='A tower can contain the same categories of hardware as a rack server: processors, memory, drives, networking and power supplies. It is often used where only a few servers are needed and no rack is installed.\n\nThe shape does not determine how powerful or reliable a server is. Specifications, serviceability, redundancy and workload suitability still matter. Several towers may require more floor space and less convenient cable organization than rack equipment.',
 points=[('Standalone cabinet','An upright case that can be placed without rack rails.'),('Expansion','Drive and card capacity depends on the particular model.'),('Environment','Space, noise, ventilation and physical access still matter.')],
 flow=['Standalone case','Internal hardware','Network connection','Office services'],
 example='A small office runs shared files and a business application on a tower server in a ventilated equipment area.',
 analogy='A freestanding cabinet rather than a shelf-mounted drawer: the container changes, but the tools inside can do similar jobs.',
 misconception='A tower server is not automatically a regular desktop, nor is it automatically slower than a rack server.',
 activity=('A small office has no rack and needs one server. Which form may fit?', ['Tower server','Loose blade without an enclosure','RAM module by itself'],0,'A tower is designed for standalone placement, subject to suitable ventilation and access.'),
 quiz=('What primarily distinguishes a tower from a rack server?', ['Its physical form and mounting','Whether it uses software','Whether it can join a network'],0,'Both can run server software and connect to networks; their physical packaging differs.'),
 spot='Find the upright dark server cabinet at the back-right.'),
 dict(id='cpu',title='CPU',kicker='The general-purpose processor',
 summary='The central processing unit executes instructions that make server software work.',
 body='A CPU carries out calculations, comparisons and control operations. A core is an execution unit within a processor; multiple cores can work on tasks concurrently. A thread is a sequence of instructions, and some processors support multiple hardware threads per core.\n\nCPU performance depends on more than clock speed. The workload, core design, memory access, cache and software all affect throughput and response time. A heatsink and airflow remove heat. The exposed CPU in the model is for teaching; operating processors need their designed cooling arrangement.',
 points=[('Core','A processing unit inside the CPU.'),('Clock speed','Cycles per second; it alone does not determine performance.'),('Cache','Small, fast memory close to the processor.')],
 flow=['Fetch instructions','Decode','Execute','Write results'],
 example='A payroll service uses the CPU to calculate salaries, apply rules and coordinate database operations.',
 analogy='A worker following instructions at a workbench. Extra workers help when the task can be divided among them.',
 misconception='Twice as many cores does not guarantee every application runs twice as fast. Some work cannot be divided easily.',
 activity=('A job can run independent calculations at once. What may help?', ['More suitable CPU cores','A larger monitor','A brighter status LED'],0,'Parallel software can distribute independent work across cores, within other system limits.'),
 quiz=('What is the CPU’s main role?', ['Execute instructions','Keep all files without power','Convert AC power into DC'],0,'Executing instructions is the CPU’s job; storage and power supplies serve different roles.'),
 spot='Find the exposed silver processor and the nearby finned CPU heatsink in the open server.'),
 dict(id='ram',title='RAM / Memory',kicker='The working space',
 summary='RAM holds the data and instructions that running software needs quickly.',
 body='Random access memory is the server’s active workspace. When a program runs, much of its working data is kept in RAM because accessing it is generally faster than reading persistent storage. Standard RAM is volatile: its contents are lost when power is removed.\n\nDIMMs are memory modules fitted into motherboard slots. Capacity, memory channels, supported speeds and placement rules depend on the platform. Many server platforms support ECC memory, which can detect and correct certain memory errors; ECC is not a backup system.',
 points=[('Capacity','How much active data can fit in memory.'),('DIMM','A module holding memory chips.'),('ECC','Error-correcting memory support on compatible systems.')],
 flow=['Load data','Hold active data','CPU reads / writes','Save results to storage'],
 example='A database keeps frequently used records in RAM to answer repeated requests quickly.',
 analogy='A workbench holds items being used now. A larger workbench can hold more items, but does not replace the storeroom.',
 misconception='Adding RAM does not automatically increase storage space. Unsaved work in RAM can disappear when power is lost.',
 activity=('The working data no longer fits in RAM. What may happen?', ['The system may use slower storage or fail an allocation','All permanent files become larger','The power supply generates more cores'],0,'Memory pressure can cause swapping and slower responses, or allocation failures depending on the system.'),
 quiz=('Which normally loses its contents when power is removed?', ['RAM','An SSD holding saved files','A printed document'],0,'Standard RAM requires power to retain working data.'),
 spot='Find the rows of upright green DIMM modules beside the CPU sockets.'),
 dict(id='motherboard',title='Motherboard',kicker='The main connection board',
 summary='The motherboard provides the sockets, slots and circuitry linking server components.',
 body='Processors sit in sockets, DIMMs fit memory slots, and expansion cards use interfaces such as PCI Express (PCIe). Power and signal routes on the motherboard let components work together. Firmware helps initialize the platform during startup.\n\nCompatibility matters: a processor or memory module must match the board and platform requirements. The motherboard is not itself the CPU or the operating system. It provides the physical and electrical foundation on which these resources operate.',
 points=[('Socket','A compatible connection for a processor.'),('Slot','A connector for memory or an expansion card.'),('PCB','Printed circuit board: conductive paths join components.')],
 flow=['CPU socket','Memory slots','Expansion interfaces','Power + control'],
 example='An engineer checks supported CPU generations, DIMM types and available PCIe lanes before planning a server upgrade.',
 analogy='The layout and connections of a workshop: stations must fit the layout and be connected correctly.',
 misconception='A physically similar connector does not guarantee electrical or firmware compatibility.',
 activity=('What should you check before replacing a CPU?', ['The board’s supported CPU list and firmware requirements','Only the CPU color','Whether the case has a handle'],0,'Socket, platform and firmware support all affect compatibility.'),
 quiz=('Which part provides CPU sockets and RAM slots?', ['Motherboard','Ethernet cable','Storage tray handle'],0,'These connectors are located on the main circuit board.'),
 spot='Find the large green circuit board beneath the processor, memory and expansion cards.'),
 dict(id='network',title='Network Interface',kicker='The link to other systems',
 summary='A network interface lets the server exchange data with clients and other networked devices.',
 body='A network interface controller (NIC) turns system data into network traffic and receives traffic from other devices. A NIC may be built into the motherboard or installed as an expansion card. Ethernet connections can use copper cables or optical links with suitable hardware.\n\nBandwidth describes a link’s capacity; latency describes delay. The effective speed also depends on switches, cabling, configuration, protocol overhead and the application. A faster NIC cannot fix every slow server. A dedicated management port serves the BMC and may be separate from application network ports.',
 points=[('NIC','Hardware connecting the server to a network.'),('Bandwidth','Capacity for data transfer over time.'),('Latency','Delay experienced by a request or packet.')],
 flow=['Application data','NIC','Switch / network','Client'],
 example='A file server sends a requested document through its NIC, across a switch, and to an employee’s laptop.',
 analogy='A loading dock connecting a building to delivery routes. Both the dock and the roads can limit traffic.',
 misconception='Network throughput is not the same as CPU performance, and the BMC port is not necessarily an application port.',
 activity=('CPU use is low, but the network link is saturated. Where should you investigate?', ['NIC, link and network path','Only CPU clock speed','Only monitor settings'],0,'The network path may be the bottleneck even if the CPU has spare capacity.'),
 quiz=('Which device carries server traffic onto the network?', ['NIC','DIMM','CPU heatsink'],0,'The NIC sends and receives network data.'),
 spot='Find the network card and Ethernet ports near the rear of the open server.'),
 dict(id='storage_interface',title='Storage Interface',kicker='The path to persistent data',
 summary='A storage interface connects drives to the server through supported protocols and hardware.',
 body='SATA and SAS are common storage connection technologies. NVMe is a storage protocol commonly carried over PCIe. A drive backplane can provide connectors behind hot-swap bays, while a controller or host interface manages communication. Some systems use RAID controllers; other systems expose drives directly.\n\nThe drive and the interface are different. A drive stores data; the interface provides a path for moving it. Connector shape alone is not enough to establish compatibility. Hot-swap capability depends on the full design, including the controller, bay, operating system and procedures.',
 points=[('Drive','The device retaining files and data.'),('Backplane','Connections behind drive bays.'),('Protocol','Rules for communicating with the storage device.')],
 flow=['CPU / memory','Storage controller or host interface','Backplane / link','SSD or HDD'],
 example='A server requests a database block through its storage interface, and the selected SSD returns the data.',
 analogy='A corridor and doorway leading to a storeroom. The route moves items; the storeroom holds them.',
 misconception='NVMe is not a form factor, and RAID is not a substitute for a backup.',
 activity=('A drive fits into a bay. Is that enough to confirm support?', ['No, protocol and system support must match','Yes, shape proves all compatibility','Yes, if its label is blue'],0,'The bay, backplane and host must support the drive’s electrical and protocol requirements.'),
 quiz=('What is the main difference between a drive and its interface?', ['The drive stores data; the interface connects it','The interface is always a CPU','There is no difference'],0,'Persistent storage and communication are distinct functions.'),
 spot='Find the backplane and blue data cables behind the front drive bays.'),
 dict(id='psu',title='Power Supply',kicker='Power the system reliably',
 summary='A power supply unit converts incoming electrical power into regulated DC power for the server.',
 body='Many servers use AC mains input and internal DC power rails. Some systems are designed for DC input. Power supply capacity must suit the server’s configuration; efficiency describes the proportion of input power delivered as useful output. Cooling removes heat created by power conversion.\n\nRedundant power supplies can maintain service after one supply fails, when the remaining supply can support the load and the system is configured accordingly. Separate upstream power paths may reduce additional single points of failure. Redundancy is not guaranteed merely by seeing two modules.',
 points=[('PSU','Power supply unit.'),('Capacity','The supported power output under specified conditions.'),('Redundancy','Additional supply capacity to tolerate some failures.')],
 flow=['Incoming power','Power conversion','Regulated DC','Server components'],
 example='A server with correctly sized redundant supplies can continue running when one module fails, while administrators replace it using approved procedures.',
 analogy='Two suitable utility feeds can offer resilience, but only if the remaining feed can handle the demand.',
 misconception='A redundant PSU does not protect against every outage. A shared upstream failure may still stop both supplies.',
 activity=('Two PSUs share the same failed upstream source. Will that guarantee service continues?', ['No','Always','Only if RAM is larger'],0,'Both supplies can lose input together. Upstream power design also matters.'),
 quiz=('What does a typical AC-input server PSU produce for components?', ['Regulated DC power','More network packets','Permanent file backups'],0,'The PSU converts and regulates electrical power.'),
 spot='Find the two removable power supply modules near the rear-right of the open server.'),
 dict(id='bmc',title='Management Controller',kicker='Manage the hardware remotely',
 summary='The baseboard management controller monitors and manages hardware independently of the main operating system.',
 body='A BMC is a small controller with its own firmware. Depending on the platform, it reports temperatures and hardware health, records events, controls power and offers a remote console. It can remain available when the main operating system is stopped, if standby power and management connectivity are present.\n\nThis is often called out-of-band management. It is separate from ordinary application traffic, although a design may share a physical network port. Management access should be restricted and maintained according to the organization’s security policy.',
 points=[('BMC','Baseboard management controller.'),('Out-of-band','Management independent of the main OS path.'),('Remote console','A way to inspect or operate the server remotely.')],
 flow=['Hardware sensors','BMC','Management network','Administrator'],
 example='An administrator checks hardware event logs and restarts an unresponsive server remotely through its management interface.',
 analogy='A building caretaker with a separate control panel who can inspect the building even when the main office is closed.',
 misconception='The BMC is not the operating system. It still requires power and appropriate connectivity to be reachable.',
 activity=('The OS is unresponsive but standby power and management networking are available. What may help?', ['BMC remote console and health logs','Changing the client wallpaper','Removing the network switch labels'],0,'A supported BMC can help diagnose hardware and access a remote console independently of the OS.'),
 quiz=('What is a typical BMC function?', ['Monitor hardware and control power remotely','Replace all CPU calculations','Store every user file'],0,'The BMC manages platform health and administration functions.'),
 spot='Find the small management chip on the motherboard; the model also includes a separate management Ethernet connector.'),
 dict(id='gpu',title='GPU / Accelerators',kicker='Specialized processing',
 summary='A GPU or other accelerator speeds up workloads suited to its specialized parallel hardware.',
 body='A graphics processing unit can perform many similar operations in parallel. Servers use GPUs for tasks such as AI training or inference, scientific computing and rendering. Other accelerators target specific workloads, such as programmable logic or dedicated AI processing.\n\nAn accelerator works with the CPU rather than replacing all of its responsibilities. Benefits depend on software support, data movement, accelerator memory, power and cooling. A server can provide many useful services without a GPU.',
 points=[('Parallel work','Many suitable operations performed concurrently.'),('PCIe','A common interface for expansion accelerators.'),('Accelerator memory','Memory local to many accelerators, separate from system RAM.')],
 flow=['CPU coordinates','Data moves to accelerator','Parallel processing','Results return'],
 example='An image-recognition service uses a GPU to process batches of images while the CPU handles requests and schedules work.',
 analogy='A specialist team doing a repeatable task in parallel while a coordinator manages the overall job.',
 misconception='A GPU does not make every program faster. Unsupported or unsuitable workloads may see no benefit.',
 activity=('Which task is often a good accelerator candidate?', ['Many similar matrix operations','Changing a file’s name once','Turning a status LED on'],0,'Matrix-heavy parallel workloads often map well to GPUs, with suitable software and sufficient data.'),
 quiz=('Does every server require a GPU?', ['No','Yes, even to store a file','Only tower servers do'],0,'GPU hardware is optional and depends on the workload.'),
 spot='Find the long PCIe accelerator card with a finned heatsink inside the open server.'),
]
BY_ID={l['id']:l for l in LESSONS}
