PHASES=[("The Tripped Line","A protection trip identifies a fault but not necessarily the inspection region."),("Electrical Evidence","Voltage and current transients carry distance-dependent information."),("Preparing Signals","Two synchronized channels become consistent 500-sample examples."),("Learning the Transient","A 1D CNN learns local waveform patterns directly in time."),("Locating the Section","Four probabilities become a line region for inspection priority."),("Protection Audit","Accuracy, neighbouring errors, and deployment limits are explicit.")]
STEPS=[
dict(id="problem",phase=0,civil="A Line Has Tripped",ai="Fault-Location Objective",tech="which 5 km section should be inspected first?",site="Protection equipment may trip a 20 km line quickly, yet field crews still need a probable location before beginning inspection.",challenge="Searching the full route delays restoration, especially where access is difficult or the line crosses multiple terrain zones.",ai_link="Classify the short voltage-current transient into one of four 5 km sections to prioritize inspection.",notebook="Define the 20 km line and four output classes.",takeaway="The output is an inspection region, not an exact repair location."),
dict(id="sections",phase=0,civil="Dividing the 20 km Line",ai="Classification Labels",tech="0-5, 5-10, 10-15, 15-20 km",site="The line is divided into four operational search regions measured from Substation A.",challenge="A continuous kilometre estimate can imply more precision than a simplified synthetic model supports.",ai_link="Assign every simulated fault distance to a transparent section label and train a four-class classifier.",notebook="Convert fault distance into Section 1–4 labels.",takeaway="Section classification keeps the educational claim aligned with model resolution."),
dict(id="physics",phase=1,civil="Voltage Collapse and Current Rise",ai="Waveform Evidence",tech="distance, impedance, resistance alter transient shape",site="A short circuit depresses voltage and increases current. Line impedance between the source and fault changes the magnitude and transient response with distance.",challenge="Fault resistance, source strength, inception angle, and noise can make simple magnitude rules ambiguous.",ai_link="Use the complete synchronized waveform so the model can combine drop, spike, oscillation, timing, and recovery shape.",notebook="Plot normal and faulted voltage/current traces.",takeaway="Distance information is distributed across the transient, not stored in one sample."),
dict(id="generate",phase=1,civil="Simulated Fault Tests",ai="Synthetic Training Data",tech="500 samples × 2 channels",site="Controlled studies vary fault distance, resistance, source strength, inception angle, and measurement noise.",challenge="A classroom notebook needs many labelled examples but cannot create real transmission-line faults.",ai_link="Generate simplified physically motivated waveforms and preserve the continuous distance as metadata only.",notebook="Create balanced examples across 0–20 km with voltage and current channels.",takeaway="Synthetic data teaches the workflow but does not validate a field protection system."),
dict(id="prepare",phase=2,civil="Preparing Relay Records",ai="Signal Normalization",tech="per-channel training statistics",site="Voltage and current use different per-unit ranges, and every record must align around the disturbance.",challenge="Scaling with test data leaks future information; scaling each record independently can erase useful magnitude differences.",ai_link="Align 500 samples and normalize each channel using training-set statistics only.",notebook="Create stratified splits and transform two channels without leakage.",takeaway="Signal preparation must preserve the distance-dependent evidence the model needs."),
dict(id="cnn",phase=3,civil="Scanning the Electrical Transient",ai="1D Convolutional Neural Network",tech="Conv1D -> pool -> Conv1D -> global average",site="Engineers inspect local events: sudden voltage reduction, current surge, damped oscillation, and recovery.",challenge="Hand-written thresholds cannot easily combine many local patterns under varying fault conditions.",ai_link="One-dimensional filters slide directly along time across both channels and learn useful transient motifs.",notebook="Build a compact Conv1D classifier ending in four Softmax outputs.",takeaway="A 1D CNN matches time-domain waveform structure without converting signals into images."),
dict(id="training",phase=3,civil="Learning From Labelled Faults",ai="Supervised Training",tech="cross-entropy + Adam + early stopping",site="Each simulated record has a known fault distance and therefore a known section.",challenge="An apparently high score can come from imbalance or leakage between nearly identical simulations.",ai_link="Use balanced sections, stratified splits, validation monitoring, and an untouched test set.",notebook="Train the CNN and plot loss and accuracy curves.",takeaway="Testing must use waveforms the CNN did not optimize against."),
dict(id="prediction",phase=4,civil="Where Should the Crew Inspect?",ai="Section Probability",tech="Softmax -> Section 1–4",site="The control room needs a probable region expressed in kilometres from Substation A.",challenge="The largest probability can still be uncertain, especially close to a section boundary.",ai_link="Report all section probabilities, confidence, and the kilometre interval; flag low-confidence cases for wider inspection.",notebook="Predict a new waveform and display the probable section and region.",takeaway="Confidence communicates uncertainty; it does not guarantee the fault lies inside the interval."),
dict(id="audit",phase=5,civil="The Protection Engineering Audit",ai="Confusion Matrix and Baseline",tech="CNN vs magnitude threshold; neighbour errors",site="A useful locator should reduce search time without misleading crews or interfering with primary protection.",challenge="Overall accuracy hides whether mistakes jump across the line or occur mainly between neighbouring sections.",ai_link="Compare with a simple magnitude baseline, inspect the confusion matrix, and count adjacent versus non-adjacent errors.",notebook="Report test metrics, inference time, confusion matrix, and field-validation exclusions.",takeaway="This model prioritizes inspection; it is not a relay, trip command, or field-validated locator.")]
BY_ID={s["id"]:s for s in STEPS};ORDER=[s["id"] for s in STEPS]

