(() => {
  'use strict';
  document.body.className = 'v2';
  const BANK = [
    {id:'overview',title:'Create and inspect the DataFrame',parts:['The records are supplied as raw_data. Create df using pd.DataFrame(raw_data).','Display the first 5 and last 5 rows, then report shape and columns.','Use dtypes and info() to identify columns that may need cleaning.'],prompt:'Explain how you created df and what its first overview tells you.'},
    {id:'describe',title:'Generate descriptive statistics',parts:['Use describe() for the available numeric columns.','Compare mean, median, minimum and maximum values.','Point out any values that appear impossible or suspicious.'],prompt:'Explain which statistics made you suspect data-quality problems.'},
    {id:'nulls',title:'Investigate missing values',parts:['Count missing values in every column.','Also check text markers such as blank strings, NA, N/A and unknown.','Display the affected rows without deleting anything yet.'],prompt:'Explain the difference between true nulls and text used to represent nulls.'},
    {id:'missing',title:'Handle missing values',parts:['Convert common missing-value markers into proper pandas missing values.','Choose drop or fill strategies appropriate to each affected column.','Save the result as cleaned_df and report remaining null counts.'],prompt:'Explain why you dropped or filled each important column.'},
    {id:'duplicates',title:'Find and remove duplicates',parts:['Count complete duplicate rows and repeated Student_ID values.','Inspect duplicates before changing the dataset.','Remove appropriate duplicates and reset the index in cleaned_df.'],prompt:'Explain why repeated identifiers may require more judgment than exact duplicate rows.'},
    {id:'types',title:'Correct data types',parts:['Clean numeric symbols or words from Score and Attendance_Percentage.','Convert Age, Score and Study_Hours to numeric values safely.','Parse Enrollment_Date and display the final dtypes.'],prompt:'Explain why errors="coerce" is useful during type conversion.'},
    {id:'text',title:'Standardize text categories',parts:['Strip extra spaces from Student_Name, Class, Gender and City.','Standardize capitalization and make equivalent class labels consistent.','Display sorted unique values before and after cleaning.'],prompt:'Explain how inconsistent categories can distort counts and analysis.'},
    {id:'invalid',title:'Validate logical ranges',parts:['Identify impossible Age, Score and Attendance_Percentage values.','Replace invalid measurements with missing values or justify another approach.','Show how many invalid values were found in each column.'],prompt:'Explain the valid ranges you selected and why.'},
    {id:'outliers',title:'Detect numeric outliers',parts:['Calculate Q1, Q3 and IQR for Study_Hours or Score.','Compute lower and upper outlier limits.','Display the outlier rows and create a boxplot.'],prompt:'Explain how IQR identifies unusual values without automatically proving they are errors.'},
    {id:'outlier_action',title:'Treat selected outliers',parts:['Choose whether to retain, remove or cap the detected outliers.','Apply your decision to cleaned_df without changing unrelated values.','Compare descriptive statistics before and after treatment.'],prompt:'Explain the effect of your outlier decision on the analysis.'},
    {id:'analysis',title:'Perform basic analysis',parts:['Calculate overall mean and median Score.','Use value_counts() for Class and Gender.','Calculate average Score and Attendance_Percentage by Class.'],prompt:'Summarize two useful findings from your basic analysis.'},
    {id:'visualize',title:'Create a cleaning report',parts:['Produce at least two charts: a score distribution and a class comparison.','Use clear titles, axis labels and an appropriate chart type.','Return cleaned_df plus a short summary of rows removed, nulls handled and types corrected.'],prompt:'Explain why each visualization is suitable and summarize the completed cleaning workflow.'}
  ];
  const LEVELS = {standard:{revealMs:10000,attempts:3,roundSeconds:300,speed:[24,31,39]},challenging:{revealMs:7000,attempts:2,roundSeconds:240,speed:[31,41,52]},expert:{revealMs:5000,attempts:2,roundSeconds:180,speed:[40,54,68]}};
  const state = {student:'',email:'',level:'expert',questionCount:12,seed:1,questions:[],round:0,answers:[],angles:[0,123,247],held:[false,false,false],attempts:[0,0,0],roundLeft:0,roundTimer:null,mediaRecorder:null,chunks:[],audioBlob:null,audioUrl:null,startedAt:null,tabLeaves:0,finished:false,freezeTimer:null,pyodide:null,pythonLoading:null,pythonDatasetReady:false,runs:0,lastRunOk:false};
  let lastFrame = performance.now();
  const $ = s => document.querySelector(s);
  const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function hash(s){let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
  function rng(){state.seed=(Math.imul(state.seed,1664525)+1013904223)>>>0;return state.seed/4294967296}
  function shuffled(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
  const DATA_COLUMNS=['Student_ID','Student_Name','Class','Gender','Age','Score','Attendance_Percentage','Study_Hours','Enrollment_Date','City','Email'];
  function dataset(){const first=['Aarav','Diya','Ishaan','Mira','Neel','Tara','Zoya','Vihaan','Kabir','Ananya','Rohan','Meera'];const cities=['Delhi','Mumbai','Bengaluru','Pune','Chennai','Kolkata'];const dates=['2026-01-12','14/02/2026','Mar 05, 2026','2026/04/18','25-05-2026','June 2 2026'];const rows=[];for(let i=0;i<48;i++){let name=first[i%first.length],cls=['10A','10B','10C'][i%3],gender=i%2?'Female':'Male',age=14+(i%4),score=55+Math.floor(rng()*43),attendance=62+Math.floor(rng()*37),hours=(1+rng()*5).toFixed(1),city=cities[i%cities.length],email=`${name.toLowerCase()}${i+1}@school.edu`;if(i===3)name='  diya ';if(i===7)name='ISHaan';if(i===11)name='';if(i===5)cls='10-A ';if(i===17)cls='Class 10B';if(i===9)gender='female ';if(i===20)gender='M';if(i===6)age='N/A';if(i===24)age=145;if(i===8)score=`${score} marks`;if(i===14)score='Absent';if(i===29)score=136;if(i===10)attendance=`${attendance}%`;if(i===22)attendance='unknown';if(i===35)attendance=117;if(i===12)hours='';if(i===31)hours=19.5;if(i===18)city=' mumbai ';if(i===27)city='DELHI';if(i===15)email='invalid-email';rows.push([1001+i,name,cls,gender,age,score,attendance,hours,dates[i%dates.length],city,email])}rows.push([...rows[4]]);rows.push([...rows[13]]);const repeated=[...rows[21]];repeated[1]='Duplicate ID Name';rows.push(repeated);rows[2][6]=null;rows[33][5]=null;return {columns:DATA_COLUMNS,rows}}

  document.body.innerHTML = `<div class="v2-shell">
  <header class="v2-top"><div class="v2-brand"><span class="v2-logo">◉</span><div><div class="v2-title">Pandas Assessment</div><div class="v2-sub">Secure Spin Reveal · reasoning + audio</div></div></div><div class="v2-stats"><span class="v2-chip" id="progressChip">Not started</span><span class="v2-chip danger" id="timerChip">--:--</span><button class="v2-btn" id="fsBtn">Fullscreen</button></div></header>
  <main class="v2-main"><section class="v2-stage"><div class="v2-kicker" id="roundLabel">Assessment preview</div><h1 class="v2-question-title" id="questionTitle">Catch each band to reveal the task</h1><div class="v2-bands" id="bands"></div><div class="v2-revealbar" id="revealBar"></div><details class="v2-data" id="dataCard" open><summary>Reference DataFrames · always available on the left</summary><div id="dataTables"></div></details></section>
  <aside class="v2-side"><section class="v2-card v2-code-card"><h2>Python coding workspace</h2><p>Write the complete pandas solution. Drafts autosave on this device for every question.</p><div class="v2-editor-wrap"><pre class="v2-lines" id="lineNumbers">1</pre><textarea class="v2-code" id="codeAnswer" spellcheck="false" placeholder="# Write your pandas code here"></textarea></div><div class="v2-editor-status"><span id="editorStats">1 line · 0 characters</span><span>Tab inserts 4 spaces · Ctrl+Enter submits</span></div></section><section class="v2-card"><h2>Required audio explanation</h2><p id="audioPrompt">Reveal the question to see the explanation prompt.</p><div class="v2-rec"><span class="v2-dot" id="recDot"></span><span id="recStatus">Not recorded</span></div><audio class="v2-audio v2-hidden" id="audioPreview" controls></audio><div class="v2-actions"><button class="v2-btn primary" id="recordBtn">Start recording</button><button class="v2-btn" id="discardBtn" disabled>Discard</button></div><div class="v2-note">Audio is recorded locally and included in the submission export. Nothing is uploaded.</div></section><section class="v2-card"><div class="v2-progress"><span id="progressBar" style="width:0"></span></div><div class="v2-actions"><button class="v2-btn primary" id="nextBtn" disabled>Next question · Ctrl+Enter</button><button class="v2-btn" id="exportBtn" disabled>Export submission</button></div><p id="gateMessage">Add code and audio to unlock the next question.</p></section></aside></main>
  <footer class="v2-foot"><span>Hold Ctrl+A, Ctrl+D or Ctrl+Q to read one part · release the keys to resume rotation</span><span id="integrityText">Focus changes: 0</span></footer></div>
  <div class="v2-modal" id="setupModal"><div class="v2-modal-card"><div class="v2-kicker">Fixed difficult assessment · 12 questions</div><h1>Pandas Spin Challenge</h1><p class="lead">Enter your identity. All students receive the same difficulty and question count, with individually randomized data and order.</p><div class="v2-grid"><div class="v2-field"><label for="studentName">Student name</label><input id="studentName" autocomplete="name"></div><div class="v2-field"><label for="studentEmail">Email address</label><input id="studentEmail" type="email" autocomplete="email"></div></div><div class="v2-error" id="setupError"></div><div class="v2-actions"><button class="v2-btn primary" id="startBtn">Begin assessment</button></div></div></div>
  <div class="v2-watermark v2-hidden" id="identityWatermark" aria-hidden="true"></div><div class="v2-freeze v2-hidden" id="freezeOverlay" role="alert" aria-live="assertive"><div class="v2-freeze-card"><div class="v2-kicker">Assessment integrity lock</div><h2>Screen frozen</h2><p>A screenshot command was detected. The assessment is temporarily locked.</p><div class="v2-freeze-time" id="freezeTime">02:00</div><p>Refreshing during this lock extends it to <strong>2 minutes 30 seconds</strong>.</p></div></div>`;

  const bandsEl=$('#bands'), revealEl=$('#revealBar');
  const codeCard=$('.v2-code-card');
  $('.v2-stats').insertAdjacentHTML('afterbegin','<div class="v2-view-toggle"><button class="v2-view-btn active" id="questionViewBtn">Question</button><button class="v2-view-btn" id="notebookViewBtn">Code notebook</button></div>');
  codeCard.insertAdjacentHTML('afterbegin','<div class="v2-notebook-title"><span id="cellQuestionLabel">QUESTION 1 · CELL 1</span><strong>Cleaning notebook</strong></div><div id="previousWork" class="v2-previous-work"></div>');
  $('#setupModal .lead').insertAdjacentHTML('afterend','<div class="v2-run-notice"><span>▶</span><span><strong>Stateful cleaning workspace</strong>The first editor creates df from raw_data. Every change you run remains available in later questions while this tab stays open.</span></div>');
  codeCard.querySelector('h2').textContent='Runnable Python workspace';
  codeCard.querySelector('p').innerHTML='The displayed records are available as <code>raw_data</code>. Create <code>df</code> once, then keep cleaning the same live DataFrame through all 12 questions.';
  codeCard.querySelector('.v2-editor-status span:last-child').textContent='Tab inserts 4 spaces · Ctrl+Enter runs';
  codeCard.querySelector('.v2-editor-wrap').insertAdjacentHTML('beforebegin','<div class="v2-runbar"><button class="v2-btn primary" id="runBtn">▶ Run code <span>Ctrl+Enter</span></button><button class="v2-btn" id="clearOutputBtn">Clear output</button><span id="pythonState">Python starts on first run</span></div>');
  $('#clearOutputBtn').insertAdjacentHTML('afterend','<button class="v2-btn" id="expandWorkspaceBtn">⛶ Expand workspace</button>');
  $('#expandWorkspaceBtn').addEventListener('click',()=>{const expanded=codeCard.classList.toggle('v2-workspace-expanded');$('#expandWorkspaceBtn').textContent=expanded?'× Restore workspace':'⛶ Expand workspace'});
  codeCard.insertAdjacentHTML('beforeend','<section class="v2-console" aria-live="polite"><div class="v2-console-head"><span><i id="runLight"></i> Output + charts</span><span id="runStatus">Not run yet</span></div><pre id="codeOutput">Click “Run code” to execute your solution.</pre><div id="chartOutput" class="v2-chart-output"></div></section>');
  codeCard.insertAdjacentHTML('beforeend','<div id="extraCells"></div><button class="v2-add-cell" id="addCellBtn">＋ Code cell for this question</button>');
  const primaryCell=document.createElement('section');primaryCell.className='v2-primary-cell';primaryCell.innerHTML='<div class="v2-cell-head"><b id="primaryCellLabel">QUESTION 1 · CELL 1</b><span>Python</span></div>';codeCard.insertBefore(primaryCell,codeCard.querySelector('.v2-runbar'));['.v2-runbar','.v2-editor-wrap','.v2-editor-status','.v2-console'].forEach(selector=>primaryCell.appendChild(codeCard.querySelector(selector)));codeCard.querySelector('.v2-notebook-title').appendChild($('#addCellBtn'));
  const audioCard=document.querySelector('.v2-side>.v2-card:nth-child(2)'),actionCard=document.querySelector('.v2-side>.v2-card:nth-child(3)');audioCard.classList.add('v2-cell-audio');actionCard.classList.add('v2-action-card');primaryCell.appendChild(audioCard);$('#addCellBtn').insertAdjacentHTML('afterend','<button class="v2-add-text" id="addTextBtn">＋ Text</button>');
  $('#nextBtn').textContent='Next question · Ctrl+Shift+Enter';
  function setView(view){document.body.dataset.assessmentView=view;$('#questionViewBtn').classList.toggle('active',view==='question');$('#notebookViewBtn').classList.toggle('active',view==='notebook')}
  $('#questionViewBtn').addEventListener('click',()=>setView('question'));$('#notebookViewBtn').addEventListener('click',()=>setView('notebook'));
  function notebookCode(){return [$('#codeAnswer').value,...Array.from(document.querySelectorAll('.v2-extra-code')).map(e=>e.value)].filter(v=>v.trim()).join('\n\n# --- next cell ---\n')}
  function refreshNotebook(){const n=state.round+1;$('#cellQuestionLabel').textContent=`QUESTION ${n} NOTEBOOK`;$('#primaryCellLabel').textContent=`QUESTION ${n} · CELL 1`;$('#extraCells').innerHTML='';$('#previousWork').innerHTML=state.answers.length?`<details><summary>Previous question code · ${state.answers.length} completed</summary>${state.answers.map((a,i)=>`<section><b>Question ${i+1}</b><pre>${esc(a.code)}</pre></section>`).join('')}</details>`:'';setView('question')}
  function addCell(){const n=state.round+1,index=document.querySelectorAll('.v2-extra-cell').length+2,cell=document.createElement('section');cell.className='v2-extra-cell';cell.innerHTML=`<div class="v2-cell-head"><b>QUESTION ${n} · CELL ${index}</b><button class="v2-cell-run">▶ Run cell</button><button class="v2-cell-delete">Delete</button></div><textarea class="v2-extra-code" spellcheck="false" placeholder="# Continue your cleaning work"></textarea><pre class="v2-cell-output">Cell not run yet.</pre><div class="v2-cell-charts"></div>`;$('#extraCells').appendChild(cell);const box=cell.querySelector('.v2-extra-code');box.addEventListener('input',updateGate);cell.querySelector('.v2-cell-delete').addEventListener('click',()=>{cell.remove();updateGate()});cell.querySelector('.v2-cell-run').addEventListener('click',async()=>{const original=$('#codeAnswer').value;$('#codeAnswer').value=box.value;await runCode();cell.querySelector('.v2-cell-output').textContent=$('#codeOutput').textContent;cell.querySelector('.v2-cell-charts').innerHTML=$('#chartOutput').innerHTML;$('#codeAnswer').value=original;updateEditor(false)});box.focus()}
  $('#addCellBtn').addEventListener('click',addCell);
  $('#addTextBtn').addEventListener('click',()=>{const n=state.round+1,index=document.querySelectorAll('.v2-text-cell').length+1,cell=document.createElement('section');cell.className='v2-text-cell';cell.innerHTML=`<div class="v2-cell-head"><b>QUESTION ${n} · NOTE ${index}</b><button class="v2-cell-delete">Delete</button></div><textarea placeholder="Add reasoning notes or markdown-style explanation…"></textarea>`;$('#extraCells').appendChild(cell);cell.querySelector('.v2-cell-delete').addEventListener('click',()=>cell.remove());cell.querySelector('textarea').focus()});
  function toast(msg){const e=document.createElement('div');e.className='v2-toast';e.textContent=msg;document.body.appendChild(e);setTimeout(()=>e.remove(),2200)}
  function table(title,cols,rows){return `<h3>${esc(title)}</h3><table><thead><tr>${cols.map(c=>`<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
  function renderRound(){
    const q=state.questions[state.round],cfg=LEVELS[state.level];state.angles=[0,123,247].map(a=>a+rng()*60);state.held=[false,false,false];state.attempts=[0,0,0];state.audioBlob=null;if(state.audioUrl)URL.revokeObjectURL(state.audioUrl);state.audioUrl=null;state.startedAt=Date.now();state.roundLeft=cfg.roundSeconds;
    clearInterval(state.roundTimer);state.roundTimer=setInterval(()=>{state.roundLeft--;paintTimer();if(state.roundLeft<=0){clearInterval(state.roundTimer);toast('Round time ended');saveRound(true)}},1000);
    $('#roundLabel').textContent=`Question ${state.round+1} of ${state.questions.length}`;$('#questionTitle').textContent=q.title;$('#audioPrompt').textContent=q.prompt;const savedDraft=localStorage.getItem(draftKey());$('#codeAnswer').value=savedDraft!==null?savedDraft:(state.round===0?'import pandas as pd\n\ndf = pd.DataFrame(raw_data)\n':'');$('#audioPreview').classList.add('v2-hidden');$('#audioPreview').removeAttribute('src');$('#recStatus').textContent='Not recorded';$('#recDot').classList.remove('live');$('#recordBtn').textContent='Start recording';$('#discardBtn').disabled=true;$('#nextBtn').disabled=true;$('#gateMessage').textContent='A code answer and an audio explanation are required.';state.lastRunOk=false;$('#codeOutput').textContent='Click “Run code” to execute this question.';$('#codeOutput').classList.remove('error');$('#chartOutput').innerHTML='';$('#runStatus').textContent='Not run yet';$('#runLight').className='';
    $('#questionTitle').textContent='Decode all three rotating parts';$('#audioPrompt').textContent=`Record your reasoning and cleaning decisions for Question ${state.round+1}. Do not simply read the prompt aloud.`;
    bandsEl.innerHTML=q.parts.map((p,i)=>`<div class="v2-band-slot"><div class="v2-band" data-band="${i}"><span class="v2-band-label">PART ${i+1}</span>${esc(p)}</div><div class="v2-mask"></div></div>`).join('');
    revealEl.innerHTML=[0,1,2].map(i=>`<div class="v2-keyhint" data-keyhint="${i}">Ctrl+${['A','D','Q'][i]}<small>hold to view part ${i+1}</small></div>`).join('');
    $('#dataTables').innerHTML=table(`Raw student dataset · ${q.data.rows.length} rows`,q.data.columns,q.data.rows);
    $('#progressChip').textContent=`${state.student} · ${state.round+1}/${state.questions.length}`;$('#progressBar').style.width=`${state.round/state.questions.length*100}%`;paintTimer();refreshNotebook();updateEditor(false);releaseParts();
  }
  function holdPart(i){if(!state.questions.length||state.finished||!$('#freezeOverlay').classList.contains('v2-hidden'))return;state.held=[false,false,false];state.held[i]=true;state.attempts[i]++;document.querySelectorAll('.v2-keyhint').forEach((el,n)=>el.classList.toggle('active',n===i));document.querySelectorAll('.v2-band-slot').forEach((el,n)=>el.classList.toggle('inactive',n!==i))}
  function releaseParts(){state.held=[false,false,false];document.querySelectorAll('.v2-keyhint').forEach(el=>el.classList.remove('active'));document.querySelectorAll('.v2-band-slot').forEach(el=>el.classList.add('inactive'))}
  function tick(now){const q=state.questions[state.round],cfg=LEVELS[state.level],dt=Math.min(.05,(now-lastFrame)/1000);lastFrame=now;if(q){document.querySelectorAll('.v2-band').forEach((el,i)=>{const dir=i===1?-1:1;if(!state.held[i])state.angles[i]+=dir*cfg.speed[i]*dt;const angle=state.angles[i],face=Math.abs(Math.cos(angle*Math.PI/180)),slot=el.parentElement;slot.style.animation='none';slot.style.transform='none';slot.style.boxShadow='none';el.style.transform=`rotateX(${angle}deg)`;el.style.opacity=String(.12+.88*face);el.style.filter=`blur(${((1-face)*1.8).toFixed(2)}px)`;el.classList.toggle('held',state.held[i])})}requestAnimationFrame(tick)}
  function paintTimer(){const m=Math.max(0,state.roundLeft);$('#timerChip').textContent=`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`}
  function draftKey(){const q=state.questions[state.round];return `pandasDraft:${state.email}:${q?.id||state.round}`}
  function updateEditor(save=true){const box=$('#codeAnswer'),value=box.value,lines=value.split('\n').length;$('#lineNumbers').textContent=Array.from({length:lines},(_,i)=>i+1).join('\n');$('#editorStats').textContent=`${lines} line${lines===1?'':'s'} · ${value.length} characters${save?' · saved':''}`;if(save&&state.email)localStorage.setItem(draftKey(),value);updateGate()}
  function loadScript(src){return new Promise((resolve,reject)=>{const old=document.querySelector(`script[src="${src}"]`);if(old){old.addEventListener('load',resolve,{once:true});old.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
  async function ensurePython(){
    if(state.pyodide)return state.pyodide;
    if(state.pythonLoading)return state.pythonLoading;
    state.pythonLoading=(async()=>{const btn=$('#runBtn');btn.disabled=true;$('#pythonState').textContent='Loading Python + pandas…';$('#runLight').className='loading';
      await loadScript('https://cdn.jsdelivr.net/pyodide/v0.27.7/full/pyodide.js');
      const py=await window.loadPyodide({indexURL:'https://cdn.jsdelivr.net/pyodide/v0.27.7/full/'});await py.loadPackage('pandas');
      py.runPython(`import ast, base64, contextlib, io, sys, traceback\ndef __run_student(code):\n    stream = io.StringIO()\n    ok = True\n    images = []\n    try:\n        tree = ast.parse(code, mode='exec')\n        with contextlib.redirect_stdout(stream), contextlib.redirect_stderr(stream):\n            for node in tree.body:\n                if isinstance(node, ast.Expr):\n                    value = eval(compile(ast.Expression(node.value), '<student>', 'eval'), globals())\n                    if value is not None:\n                        print(value)\n                else:\n                    unit = ast.Module(body=[node], type_ignores=[])\n                    exec(compile(unit, '<student>', 'exec'), globals())\n        if 'matplotlib.pyplot' in sys.modules:\n            import matplotlib.pyplot as plt\n            for number in plt.get_fignums():\n                buffer = io.BytesIO()\n                plt.figure(number).savefig(buffer, format='png', bbox_inches='tight', dpi=120)\n                images.append(base64.b64encode(buffer.getvalue()).decode('ascii'))\n            plt.close('all')\n    except Exception:\n        ok = False\n        traceback.print_exc(file=stream)\n    return ok, stream.getvalue(), images`);
      state.pyodide=py;$('#pythonState').textContent='Python + pandas ready';$('#runLight').className='ready';btn.disabled=false;return py})().catch(err=>{state.pythonLoading=null;$('#pythonState').textContent='Python could not load';$('#runLight').className='error';$('#runBtn').disabled=false;throw err});
    return state.pythonLoading;
  }
  async function runCode(){if(!state.questions.length||state.finished)return;const code=$('#codeAnswer').value;if(!code.trim()){toast('Write some Python code first');return}const btn=$('#runBtn'),out=$('#codeOutput'),charts=$('#chartOutput'),started=performance.now();btn.disabled=true;btn.textContent='Running…';out.textContent='Preparing Python environment…';charts.innerHTML='';$('#runStatus').textContent='Running';$('#runLight').className='loading';
    try{const py=await ensurePython(),d=state.questions[state.round].data;await py.loadPackagesFromImports(code);if(!state.pythonDatasetReady){py.globals.set('_raw_json',JSON.stringify(d.rows));py.globals.set('_columns_json',JSON.stringify(d.columns));py.runPython(`import json\n_columns = json.loads(_columns_json)\nraw_data = [dict(zip(_columns, row)) for row in json.loads(_raw_json)]`);state.pythonDatasetReady=true}py.globals.set('_student_code',code);const result=await py.runPythonAsync('__run_student(_student_code)');const values=result.toJs({create_proxies:false});result.destroy();const ok=Boolean(values[0]),text=String(values[1]||''),images=Array.from(values[2]||[]);state.runs++;state.lastRunOk=ok;out.textContent=text||(ok?'Code completed successfully (no text output).':'Execution failed without an error message.');out.classList.toggle('error',!ok);images.forEach((data,i)=>{const img=document.createElement('img');img.src=`data:image/png;base64,${data}`;img.alt=`Python chart ${i+1}`;charts.appendChild(img)});$('#runLight').className=ok?'ready':'error';$('#runStatus').textContent=`${ok?'Completed':'Error'} · workspace preserved · ${images.length} chart${images.length===1?'':'s'} · ${((performance.now()-started)/1000).toFixed(2)}s`;updateGate()}catch(err){state.lastRunOk=false;out.textContent=`Runner error: ${err.message||err}`;out.classList.add('error');$('#runLight').className='error';$('#runStatus').textContent='Runner unavailable'}finally{btn.disabled=false;btn.innerHTML='▶ Run code <span>Ctrl+Enter</span>'}}
  function updateGate(){const hasCode=notebookCode().trim().length>0,hasRun=state.lastRunOk,hasAudio=!!state.audioBlob,ready=hasCode&&hasRun&&hasAudio;$('#nextBtn').disabled=!ready;$('#gateMessage').textContent=ready?'Next question unlocked — executed code and audio are complete.':`${hasCode?'✓ Code added':'○ Add code'} · ${hasRun?'✓ Code ran successfully':'○ Run code successfully'} · ${hasAudio?'✓ Audio recorded':'○ Record audio for this question'}`}
  async function toggleRecord(){if(state.mediaRecorder&&state.mediaRecorder.state==='recording'){state.mediaRecorder.stop();return}if(!navigator.mediaDevices?.getUserMedia){toast('Microphone recording is unavailable in this browser');return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});state.chunks=[];state.mediaRecorder=new MediaRecorder(stream);state.mediaRecorder.ondataavailable=e=>{if(e.data.size)state.chunks.push(e.data)};state.mediaRecorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());state.audioBlob=new Blob(state.chunks,{type:state.mediaRecorder.mimeType||'audio/webm'});state.audioUrl=URL.createObjectURL(state.audioBlob);$('#audioPreview').src=state.audioUrl;$('#audioPreview').classList.remove('v2-hidden');$('#recStatus').textContent=`Recorded · ${Math.ceil(state.audioBlob.size/1024)} KB`;$('#recDot').classList.remove('live');$('#recordBtn').textContent='Re-record';$('#discardBtn').disabled=false;updateGate()};state.mediaRecorder.start();$('#recDot').classList.add('live');$('#recStatus').textContent='Recording… explain your reasoning';$('#recordBtn').textContent='Stop recording'}catch(e){toast('Microphone permission was not granted')}}
  function discardAudio(){if(state.audioUrl)URL.revokeObjectURL(state.audioUrl);state.audioBlob=null;state.audioUrl=null;$('#audioPreview').classList.add('v2-hidden');$('#recStatus').textContent='Not recorded';$('#recordBtn').textContent='Start recording';$('#discardBtn').disabled=true;updateGate()}
  function saveRound(timedOut=false){if(state.finished)return;const q=state.questions[state.round];state.answers.push({questionId:q.id,title:q.title,code:notebookCode(),cellCount:1+document.querySelectorAll('.v2-extra-cell').length,secondsUsed:LEVELS[state.level].roundSeconds-state.roundLeft,revealAttempts:[...state.attempts],timedOut,audioBlob:state.audioBlob,audioType:state.audioBlob?.type||null});localStorage.removeItem(draftKey());if(state.round<state.questions.length-1){state.round++;renderRound()}else finish()}
  function finish(){state.finished=true;clearInterval(state.roundTimer);releaseParts();$('#progressBar').style.width='100%';$('#progressChip').textContent='Assessment complete';$('#timerChip').textContent='DONE';$('#nextBtn').disabled=true;$('#exportBtn').disabled=false;$('#gateMessage').textContent='Export the submission package and give all downloaded files to the instructor.';toast('Assessment complete')}
  function download(name,blob){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
  function exportSubmission(){const token=hash(state.email).toString(16),stem=`pandas_${token}_${new Date().toISOString().replace(/[:.]/g,'-')}`,manifest={student:state.student,email:state.email,difficulty:'fixed-expert',questionCount:12,seed:hash(state.email),tabLeaves:state.tabLeaves,submittedAt:new Date().toISOString(),answers:state.answers.map((a,i)=>({...a,audioBlob:undefined,audioFile:a.audioBlob?`${stem}_q${i+1}.webm`:null}))};download(`${stem}.json`,new Blob([JSON.stringify(manifest,null,2)],{type:'application/json'}));state.answers.forEach((a,i)=>{if(a.audioBlob)download(`${stem}_q${i+1}.webm`,a.audioBlob)});toast('Submission files downloaded')}
  const FREEZE_KEY='pandasAssessmentFreezeUntil';
  function showFreeze(until){releaseParts();const overlay=$('#freezeOverlay');overlay.classList.remove('v2-hidden');clearInterval(state.freezeTimer);const paint=()=>{const left=Math.max(0,until-Date.now());if(left<=0){localStorage.removeItem(FREEZE_KEY);overlay.classList.add('v2-hidden');clearInterval(state.freezeTimer);return}const sec=Math.ceil(left/1000);$('#freezeTime').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`};paint();state.freezeTimer=setInterval(paint,250)}
  function triggerFreeze(){const until=Date.now()+120000;localStorage.setItem(FREEZE_KEY,String(until));showFreeze(until)}
  function restoreFreeze(){const saved=Number(localStorage.getItem(FREEZE_KEY)||0);if(saved>Date.now()){const extended=Date.now()+150000;localStorage.setItem(FREEZE_KEY,String(extended));showFreeze(extended)}else localStorage.removeItem(FREEZE_KEY)}
  function updateWatermark(){if(!state.email)return;const stamp=new Date().toLocaleString();$('#identityWatermark').innerHTML=Array.from({length:18},()=>`<span>${esc(state.student)}\n${esc(state.email)}\n${esc(stamp)}</span>`).join('')}
  function start(){const name=$('#studentName').value.trim(),email=$('#studentEmail').value.trim().toLowerCase();if(name.length<2||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){$('#setupError').textContent='Enter a valid student name and email address.';return}state.student=name;state.email=email;state.seed=hash(`${email}|${name}`);const raw=dataset();state.questions=BANK.map(q=>({...q,data:raw}));$('#setupModal').classList.add('v2-hidden');$('#identityWatermark').classList.remove('v2-hidden');updateWatermark();setInterval(updateWatermark,30000);renderRound();requestAnimationFrame(tick)}
  $('#startBtn').addEventListener('click',start);$('#fsBtn').addEventListener('click',()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.());$('#codeAnswer').addEventListener('input',()=>{state.lastRunOk=false;updateEditor(true)});$('#codeAnswer').addEventListener('scroll',()=>{$('#lineNumbers').scrollTop=$('#codeAnswer').scrollTop});$('#codeAnswer').addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();const box=e.currentTarget,start=box.selectionStart,end=box.selectionEnd;box.setRangeText('    ',start,end,'end');updateEditor(true)}});$('#runBtn').addEventListener('click',runCode);$('#clearOutputBtn').addEventListener('click',()=>{$('#codeOutput').textContent='Output cleared.';$('#chartOutput').innerHTML='';$('#codeOutput').classList.remove('error');$('#runStatus').textContent='Cleared';$('#runLight').className=''});$('#recordBtn').addEventListener('click',toggleRecord);$('#discardBtn').addEventListener('click',discardAudio);$('#nextBtn').addEventListener('click',()=>saveRound(false));$('#exportBtn').addEventListener('click',exportSubmission);
  window.addEventListener('keydown',e=>{const key=(e.key||'').toLowerCase();if(e.key==='PrintScreen'||(e.metaKey&&e.shiftKey&&key==='s')){e.preventDefault();triggerFreeze();return}if((e.ctrlKey||e.metaKey)&&key==='enter'){e.preventDefault();if(e.shiftKey){if($('#nextBtn').disabled)toast('Complete the code and audio explanation first');else saveRound(false)}else runCode();return}if(e.repeat||!(e.ctrlKey||e.metaKey))return;const i={a:0,d:1,q:2}[key];if(i!==undefined){e.preventDefault();holdPart(i)}},{capture:true});
  window.addEventListener('keyup',e=>{const key=(e.key||'').toLowerCase();if(['a','d','q','control','meta'].includes(key))releaseParts()},{capture:true});
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.questions.length&&!state.finished){state.tabLeaves++;$('#integrityText').textContent=`Focus changes: ${state.tabLeaves}`}});
  window.addEventListener('beforeunload',e=>{if(state.questions.length&&!state.finished){e.preventDefault();e.returnValue=''}});
  restoreFreeze();
})();
