PHASES=[("The Site Logistics Problem","One crane location must serve weighted lifting demand."),("Engineering Constraints","Reach, obstacles, and exclusion zones define feasibility."),("Learning the Cost Surface","An MLP approximates expensive candidate evaluation."),("Searching for Placement","A genetic algorithm explores the learned surface."),("Verifying the Recommendation","The selected point is checked with exact geometry."),("Project Audit","Surrogate error, constraints, and planning limitations are explicit.")]
STEPS=[
dict(id="problem",phase=0,civil="Where Should the Tower Crane Stand?",ai="Placement Optimization Objective",tech="recommended X,Y coordinates",site="A tower crane must serve material-delivery points scattered across a bounded construction site.",challenge="A poor location increases slewing and trolley travel, may leave lifts beyond reach, and can conflict with obstacles or prohibited zones.",ai_link="Search candidate coordinates for the lowest feasible weighted lifting effort.",notebook="Define the 80×60 m site and placement output.",takeaway="The recommendation is a coordinate supported by an explicit objective and constraints."),
dict(id="demand",phase=0,civil="Lift Points and Daily Frequency",ai="Weighted Demand",tech="Σ frequency × distance",site="A concrete core requiring forty lifts per day should influence placement more than a delivery point used three times.",challenge="Minimizing unweighted average distance can optimize rare lifts while penalizing repetitive site logistics.",ai_link="Multiply each crane-to-lift distance by its expected lift frequency.",notebook="Create lift coordinates, frequencies, and weighted-distance calculations.",takeaway="Frequency converts geometric distance into operational lifting effort."),
dict(id="constraints",phase=1,civil="Reach and Unsafe Areas",ai="Feasibility Constraints",tech="boom radius + obstacle and safety-zone checks",site="The crane base cannot occupy a building, temporary structure, or exclusion zone, and required lift points must lie within boom reach.",challenge="A mathematically short location is useless if it is unsafe or cannot reach the workface.",ai_link="Separate feasibility checks from the distance objective and penalize violations strongly during search.",notebook="Represent rectangles, boom reach, site boundary, and reachability.",takeaway="Constraints define what can be built; optimization chooses among feasible positions."),
dict(id="cost",phase=1,civil="The Exact Placement Score",ai="Engineering Objective Function",tech="weighted distance + unreachable and safety penalties",site="Planners need a transparent score that distinguishes efficient feasible points from unsafe or unreachable points.",challenge="Penalty values must dominate normal travel cost without hiding which constraint failed.",ai_link="Calculate exact distance cost and attach named penalties for each violation.",notebook="Implement the exact evaluator and test several candidate positions.",takeaway="A cost function is an engineering specification written as arithmetic."),
dict(id="dataset",phase=2,civil="Thousands of Candidate Locations",ai="Surrogate Training Data",tech="candidate X,Y + fixed site encoding -> exact cost",site="Evaluating a dense candidate grid or many evolving layouts can require repeated geometric checks.",challenge="A neural surrogate is only useful if its training candidates cover safe, unsafe, reachable, and boundary regions.",ai_link="Sample thousands of positions, compute exact costs, and train on the resulting candidate table.",notebook="Generate candidate coordinates and exact labels across the site.",takeaway="The surrogate can only learn portions of the cost surface represented in its examples."),
dict(id="surrogate",phase=2,civil="Learning How Good a Position Is",ai="MLP Cost Surrogate",tech="candidate/site features -> predicted cost",site="The same geometric evaluator may be called repeatedly by a search algorithm.",challenge="The cost surface contains sharp penalty boundaries that a smooth network can approximate poorly.",ai_link="Train an MLP regressor to estimate cost quickly while retaining exact verification for final decisions.",notebook="Build and train the surrogate, then plot predicted cost contours.",takeaway="A surrogate accelerates search; it does not replace the exact engineering evaluator."),
dict(id="audit",phase=2,civil="Checking the Learned Cost Surface",ai="Surrogate Error Audit",tech="MAE, safe-region error, ranking agreement",site="Placement depends more on selecting the right low-cost region than matching every huge penalty exactly.",challenge="A low global error can hide poor ranking among feasible candidates or false predictions near exclusion boundaries.",ai_link="Measure overall error, feasible-only error, top-candidate ranking agreement, and boundary cases.",notebook="Compare predicted and exact costs on unseen positions.",takeaway="Audit the decisions the surrogate will influence, not only its average numeric error."),
dict(id="search",phase=3,civil="Evolving Better Crane Positions",ai="Genetic Algorithm",tech="select, crossover, mutate candidate coordinates",site="The planner wants a good position without checking every centimetre of the site.",challenge="Search can converge to a surrogate error or an unsafe boundary if constraints are not respected.",ai_link="Evolve populations on predicted cost, clip to site limits, and preserve diverse candidates.",notebook="Run a compact GA and plot best cost by generation.",takeaway="The optimizer proposes; the exact evaluator verifies."),
dict(id="verify",phase=4,civil="The Verified Crane Recommendation",ai="Exact Post-Optimization Check",tech="coordinates, reach, violations, exact cost",site="Before a location is reported, planners need its reach coverage, safety status, and lifting-effort metrics.",challenge="A surrogate optimum is not acceptable until the original objective and every constraint are recalculated.",ai_link="Evaluate the best GA candidates exactly, choose the best feasible one, and compare it with a baseline position.",notebook="Display before/after maps, reach circle, metrics, and limitations.",takeaway="Only an exactly verified feasible candidate becomes the educational recommendation.")]
BY_ID={s["id"]:s for s in STEPS};ORDER=[s["id"] for s in STEPS]

