"""Shared teaching registry for dam pre-release decision support."""
PHASES=[("The Operating Dilemma","Flood storage and stored-water security compete."),("Reading the Catchment","Six measurements summarize the current event."),("Learning Storm Response","An MLP learns future reservoir level."),("Choosing a Release","A transparent rule checks reservoir and downstream safety."),("Scenario Test","AI pre-release is compared with waiting."),("Engineering Audit","Assumptions, errors, and authority limits are explicit.")]
STEPS=[
dict(id="dilemma",phase=0,civil="One Reservoir, Two Duties",ai="Multi-Objective Decision",tech="flood safety vs conserved storage",site="Before a forecast storm, the dam stores water for supply, irrigation, and power while also needing empty space to absorb inflow.",challenge="Release too little and an emergency spill may be required later. Release too much and valuable storage is lost if the forecast is wrong.",ai_link="Prediction supplies an early view of the reservoir level expected after six hours; a separate engineering rule turns that forecast into a cautious release.",notebook="Define the operating objective and the no-pre-release baseline.",takeaway="The goal is not maximum release or maximum storage; it is a defensible balance."),
dict(id="inputs",phase=1,civil="Six Conditions Before the Storm",ai="Input Features",tech="level, rain, inflow, downstream, free storage, release",site="Operators know how full the reservoir is, expected rainfall, current inflow, downstream river state, remaining storage, and current release.",challenge="Each variable changes the consequence of the others: a high reservoir with low rainfall is different from the same level before an extreme storm.",ai_link="Use exactly six summarized inputs so the student model remains explainable and does not require a long time sequence.",notebook="Generate synthetic event rows with the six inputs and a six-hour future-level target.",takeaway="The input row is a compact engineering snapshot of the coming event."),
dict(id="data",phase=1,civil="Recorded Storm Events",ai="Training Dataset",tech="hydrologic mass-balance simulation",site="Past events pair pre-storm conditions with observed inflow, release, evaporation, spill, and final reservoir level.",challenge="A useful teaching dataset must obey storage balance; arbitrary random percentages can produce impossible reservoir behaviour.",ai_link="Generate examples from a simplified water-balance model, then reserve later events for testing.",notebook="Simulate storm volume and future storage from consistent units.",takeaway="Synthetic data should still respect conservation of mass."),
dict(id="prepare",phase=2,civil="Putting Measurements on One Scale",ai="Normalization",tech="training-only StandardScaler",site="Rainfall is measured in millimetres, flow in cubic metres per second, and levels in percentages.",challenge="Raw numerical size can make a neural network treat units as importance, and fitting a scaler on test events leaks future information.",ai_link="Fit the scaler on training rows only and transform validation and test rows with those same parameters.",notebook="Create time-ordered splits and scale six features without leakage.",takeaway="The scaler is part of the prediction system and must travel with the model."),
dict(id="mlp",phase=2,civil="Forecasting the Six-Hour Level",ai="Feedforward Neural Network",tech="6 -> Dense64 -> Dense32 -> Dense16 -> 1",site="The decision uses one summarized snapshot rather than a long sensor sequence.",challenge="The relation between rainfall, catchment inflow, storage, and release is nonlinear, especially near full reservoir conditions.",ai_link="An MLP combines the six inputs through dense layers and outputs one continuous future-level percentage.",notebook="Train a compact regression MLP with MAE loss and early stopping.",takeaway="Use the simplest model architecture that matches the way the inputs are represented."),
dict(id="decision",phase=3,civil="Selecting a Pre-Release",ai="Constrained Decision Layer",tech="forecast band + downstream cap",site="A high forecast level suggests creating space, but the river below the dam may already be high and unable to receive a large release safely.",challenge="A model forecast alone does not decide what is operationally permissible downstream.",ai_link="Map predicted level to a proposed release, then cap it according to downstream river condition. Keep this rule visible and editable.",notebook="Apply project-assumption bands and downstream release caps.",takeaway="Prediction estimates what may happen; engineering constraints govern what may be done."),
dict(id="compare",phase=4,civil="Wait Versus Act Early",ai="Scenario Simulation",tech="no pre-release vs constrained AI pre-release",site="Waiting preserves all water before the storm but may force a large spill at the peak. Acting early creates storage while downstream capacity is still available.",challenge="A recommendation is meaningful only if it reduces peak level or emergency spill without unnecessarily sacrificing retained water.",ai_link="Run the same simulated storm twice and compare peak level, emergency spill, early release, retained storage, and downstream risk.",notebook="Calculate a side-by-side scenario table and storage curves.",takeaway="Judge the policy by both flood protection and water retained after the event."),
dict(id="audit",phase=5,civil="The Dam Safety Audit",ai="Model and Policy Evaluation",tech="MAE, RMSE, high-level misses, sensitivity",site="Dam releases are high-consequence decisions governed by operating rules, forecasts, instrumentation, and responsible authorities.",challenge="A low average prediction error can hide underprediction during the rare extreme events that matter most.",ai_link="Audit regression error, high-level underprediction, forecast sensitivity, and rule behaviour separately. Never present this notebook as autonomous control.",notebook="Report test metrics, extreme-event errors, assumptions, and deployment exclusions.",takeaway="A student model can illustrate decision support; it cannot authorize a real dam release.")]
BY_ID={s["id"]:s for s in STEPS};ORDER=[s["id"] for s in STEPS]

