"""Five-part teaching registry shared by the app and notebook."""
PHASES=[("See the space","A crowded scene becomes a grid."),("Protect access","Graphs and constraints keep a route open."),
        ("Coordinate people","Roles, sensors and one instruction at a time."),("Adapt safely","Replan gently, test failures and hand control back.")]
STEPS=[
dict(id="scene",phase=0,scene="A Collapse In A Crowded Station",ai="The Floor Becomes A Coordinator",tech="12 × 12 tiles · door · bench · crowd · helpers",site="A person collapses beside a bench. Four helpers arrive from different directions while responders approach from the east.",challenge="Useful people and equipment can still form a wall around the person and block the only route in.",ai_link="The mat maps usable tiles, obstacles, entrances and occupied space before assigning any position.",notebook="Phases 1–2: build the scene and measure a manual layout.",takeaway="The first layout problem is access, not treatment."),
dict(id="rules",phase=0,scene="Nearest Is Not Always Safest",ai="The First Placement Rules",tech="nearest free tile · nearest kit position",site="In an empty hall, putting everything near the person seems sensible.",challenge="Beside a wall or bench, the nearest tiles may close the approach corridor or overlap roles.",ai_link="Simple rules create a baseline whose failures can be inspected tile by tile.",notebook="Phase 3: rule-based placement.",takeaway="A locally convenient tile can block the whole scene."),
dict(id="graph",phase=1,scene="Every Usable Tile Is A Node",ai="Graph Model And A* Route",tech="nodes · neighbours · connected regions · shortest safe path",site="Responders need a continuous lane from the entrance to the required side of the scene.",challenge="The shortest line may run through a bench, crowd or assigned equipment position.",ai_link="A graph search removes unusable nodes and finds a route that remains connected.",notebook="Phases 4–5: graph model and responder lane.",takeaway="An access route is a connected promise, not a painted arrow."),
dict(id="optimize",phase=1,scene="A Layout With Hard Boundaries",ai="Constrained Optimization",tech="access and hazard penalties dominate convenience",site="The primary helper must be near the person; the kit must be reachable; nobody may occupy the responder lane.",challenge="Optimizing each role separately creates collisions between otherwise sensible choices.",ai_link="The optimizer evaluates a complete arrangement and rejects layouts that break hard constraints.",notebook="Phases 6–7: constraints and optimization.",takeaway="Safety constraints reject; soft costs rank what remains."),
dict(id="roles",phase=2,scene="Give People Named Jobs",ai="Weighted Role Assignment",tech="verified training · mobility · fatigue · current task",site="Four helpers differ in location, mobility, fatigue and whether training was verified.",challenge="Appearance cannot establish competence, and repeatedly changing jobs creates confusion.",ai_link="Matching minimizes assignment cost using declared or verified facts only.",notebook="Phase 8: helper-to-role assignment.",takeaway="Assign from known capabilities, never inferred identity."),
dict(id="sensors",phase=2,scene="The Mat Checks What Actually Happened",ai="Pressure-Sensor Verification",tech="occupied · expected zone · stuck/noisy/missing sensor",site="Green footprints are useful only if the helper reaches them and the access lane stays empty.",challenge="A heavy kit and a kneeling person may produce similar pressure, while a failed tile can report either forever.",ai_link="Temporal sensor events verify occupancy and raise a fault without guessing who or what is present.",notebook="Phases 9–10: pressure stream and priority feedback.",takeaway="One clear instruction follows the highest verified problem."),
dict(id="replan",phase=3,scene="Change The Minimum Necessary",ai="Dynamic Replanning",tech="new layout cost + λ × people moved",site="A chair blocks the route, a helper arrives, or responders switch entrances.",challenge="A technically better layout can become worse if every footprint moves at once.",ai_link="The reconfiguration penalty preserves unaffected assignments and moves only what the new constraint requires.",notebook="Phase 11: dynamic obstruction and stable replanning.",takeaway="Adapt the scene without making the people chase the algorithm."),
dict(id="fatigue",phase=3,scene="Prepare The Handover Before It Is Needed",ai="Fatigue-Aware Rotation",tech="yellow preparation zone · dispatcher-approved handover",site="A primary helper becomes tired while a replacement waits nearby.",challenge="A late replacement interrupts assistance; unnecessary rotation adds another collision between helpers.",ai_link="The mat prepares a position but leaves treatment timing to approved protocols and the dispatcher.",notebook="Phase 12: helper-fatigue rotation.",takeaway="Prepare space for a handover; do not invent when treatment changes."),
dict(id="environments",phase=3,scene="One Pattern Does Not Fit Every Place",ai="Environment And Equipment Tests",tech="hall · platform · bus aisle · partial mat · multiple kits",site="A railway platform, classroom and bus aisle have different doors, widths and obstacles.",challenge="A static pattern that works in a hall can make a narrow aisle unusable.",ai_link="The same constraints are solved on different geometries and equipment arrival directions.",notebook="Phases 13–14: environments and multiple equipment items.",takeaway="Keep the safety rules; recompute the geometry."),
dict(id="benchmark",phase=3,scene="Did The Mat Organize The Scene?",ai="Controller Benchmark",tech="blockage · conflicts · movement · equipment distance",site="The same synthetic scene is replayed with no mat, printed markings, rules, optimization and dynamic replanning.",challenge="A neat-looking arrangement may still block responders or move helpers unnecessarily.",ai_link="The score keeps access and hazards dominant and reports every component separately.",notebook="Phase 15 and the final experiments.",takeaway="Measure access and human disruption, not an invented medical outcome."),]
BY_ID={s["id"]:s for s in STEPS}; ORDER=[s["id"] for s in STEPS]
